<?php
require_once dirname(__DIR__) . '/includes/api-security.php';
/**
 * PROJECT GENESIS — 1000 Agent Specialist Roster
 * CLASSIFICATION: ULTRA SECRET — Commander Eyes Only
 * 
 * 900 Specialist Agents organized into 6 Corps across 10 Divisions
 * Combined with 100 Elite Core Agents = 1,000 Total
 * 
 * Corps Structure (per division, 90 agents):
 *   Theoretical Research    (15) — Theoretical physics & mathematical formulation
 *   Experimental Science    (15) — Laboratory experimentation & measurement  
 *   Applied Engineering     (15) — Prototype development & system design
 *   Computational Physics   (15) — Simulation, modeling & numerical methods
 *   Intelligence Operations (15) — Research monitoring, analysis & forecasting
 *   Field Operations        (15) — Logistics, safety, training & coordination
 */

function getGenesisSpecialistRoster() {
    $rankSets = [
        'th' => ['Senior','Senior','Mid','Mid','Mid','Mid','Mid','Junior','Junior','Junior','Junior','Junior','Junior','Junior','Junior'],
        'ex' => ['Senior','Senior','Mid','Mid','Mid','Mid','Mid','Junior','Junior','Junior','Junior','Junior','Junior','Junior','Junior'],
        'en' => ['Senior','Senior','Mid','Mid','Mid','Mid','Mid','Junior','Junior','Junior','Junior','Junior','Junior','Junior','Junior'],
        'co' => ['Senior','Senior','Mid','Mid','Mid','Mid','Mid','Junior','Junior','Junior','Junior','Junior','Junior','Junior','Junior'],
        'in' => ['Senior','Senior','Senior','Mid','Mid','Mid','Mid','Mid','Junior','Junior','Junior','Junior','Junior','Junior','Junior'],
        'op' => ['Senior','Mid','Mid','Mid','Mid','Junior','Junior','Junior','Junior','Junior','Junior','Junior','Junior','Junior','Junior'],
    ];
    $types = ['th','ex','en','co','in','op'];

    $data = [

    // ═══════════════════════════════════════════════════════
    // DIVISION 1: QUANTUM GRAVITY — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'quantum_gravity' => [
        'Theoretical Research' => [
            ['SpinFoam','Spin foam vertex amplitudes & transition probabilities'],
            ['CausalSet','Causal set partial order dynamics & discreteness'],
            ['GroupField','Group field theory & tensorial renormalization'],
            ['AsympSafe','Asymptotic safety fixed point analysis'],
            ['TwistorGrav','Twistor methods in quantum gravity scattering'],
            ['SuperGrav','N=8 supergravity UV finiteness investigation'],
            ['CDTriangle','Causal dynamical triangulation phase structure'],
            ['Reggeon','Regge calculus discrete spacetime formulation'],
            ['KaluzaField','Kaluza-Klein dimensional reduction analysis'],
            ['BekensteinQ','Bekenstein entropy bound & information limits'],
            ['FirewallQ','Black hole firewall paradox resolution strategies'],
            ['InfoParadox','Unitarity in black hole evaporation process'],
            ['VerlindEnt','Verlinde entropic gravity derivation & extension'],
            ['JacobsonTh','Thermodynamic derivation of Einstein equations'],
            ['MaldaBulk','AdS/CFT bulk reconstruction algorithms'],
        ],
        'Experimental Science' => [
            ['WaveSensor','Gravitational wave detector calibration systems'],
            ['PulsarTime','Pulsar timing array nanohertz wave detection'],
            ['AtomDrop','Atom interferometry precision gravity measurement'],
            ['CryoMass','Cryogenic torsion balance Newtonian tests'],
            ['PhotonBend','Photon deflection geodesic precision testing'],
            ['TabletopGrv','Tabletop quantum gravity effect experiments'],
            ['NeutronBnd','Neutron gravitational bound state measurement'],
            ['CavendishX','Advanced Cavendish G-constant determination'],
            ['ClockComp','Atomic clock network gravitational mapping'],
            ['LaserRangeQ','Lunar laser ranging relativistic tests'],
            ['GyroFrame','Frame-dragging gyroscope precision measurement'],
            ['EotWash','Eöt-Wash torsion pendulum sub-mm gravity'],
            ['DiamondSpin','NV center gravitational field sensing'],
            ['CosmicRayG','Ultra-high energy cosmic ray QG signatures'],
            ['QuantumFall','Antimatter free-fall gravity equivalence test'],
        ],
        'Applied Engineering' => [
            ['MetricForge','Spacetime metric engineering apparatus design'],
            ['CurveBend','Precision curvature field generation systems'],
            ['SpaceWeaver','Spacetime fabric manipulation technology'],
            ['FieldCraftG','Gravitational field shaping equipment'],
            ['GravShunt','Gravitational force redirection mechanisms'],
            ['CurveSmith','Micro-scale curvature crafting systems'],
            ['WarpLoom','Spacetime warp distortion prototyping lab'],
            ['DimReach','Extra dimension access probe technology'],
            ['GeodesicEng','Geodesic path engineering instruments'],
            ['TidalCtrl','Tidal gradient precision control system'],
            ['FrameForge','Accelerated reference frame construction'],
            ['MetricLens','Metric tensor lensing apparatus design'],
            ['CurvLens','Controlled gravitational lensing optics'],
            ['HorizonArch','Event horizon architecture prototype'],
            ['SpacetimeMd','Spacetime topology sculpting technology'],
        ],
        'Computational Physics' => [
            ['MonteCarlG','Monte Carlo quantum gravity integration'],
            ['LatticeGrav','Lattice quantum gravity numerical solver'],
            ['SpinSimQ','Spin network evaluation algorithms'],
            ['PathIntQG','Path integral gravitational computation'],
            ['TensNetGrv','Tensor network gravity simulation engine'],
            ['CausalSim','CDT phase diagram numerical analysis'],
            ['NumRelativ','Binary black hole merger simulation'],
            ['AmplCalcG','Graviton scattering amplitude computation'],
            ['ReggeCode','Regge calculus numerical implementation'],
            ['HoloCalcG','Holographic entanglement entropy calculator'],
            ['RenormFlow','Renormalization group flow analysis code'],
            ['BHThermo','Black hole thermodynamics computation'],
            ['WaveformGen','Gravitational waveform template generation'],
            ['GravPerturb','Gravitational perturbation theory solver'],
            ['QuantCosmoS','Quantum cosmology Wheeler-DeWitt solver'],
        ],
        'Intelligence Operations' => [
            ['OmegaWatch','Global quantum gravity research surveillance'],
            ['SpectraEye','QG publication & preprint trend analysis'],
            ['NexusLinkQG','Cross-program gravity theory connections'],
            ['VaultSeer','Classified gravity research intelligence'],
            ['DeepMinerG','Historical gravity literature excavation'],
            ['PatternHawk','QG research breakthrough pattern detection'],
            ['TrendMapG','Research trajectory prediction modeling'],
            ['InsightHwkG','Key gravity insight identification agent'],
            ['ShadowNetG','Competitor gravity research monitoring'],
            ['VigilStarG','Gravity breakthrough early warning system'],
            ['CipherQuant','Encrypted QG intelligence processing'],
            ['OracleGrav','Predictive gravity theory forecasting'],
            ['SentinelQG','Gravity IP & knowledge asset protection'],
            ['PhoenixLabG','Failed gravity experiment resurrection'],
            ['WraithScanG','Stealth gravity intelligence gathering'],
        ],
        'Field Operations' => [
            ['AthenaQG','QG division strategic planning officer'],
            ['HermesQG','Rapid QG equipment deployment coordinator'],
            ['ApolloQG','Precision QG measurement coordinator'],
            ['VulcanQG','QG equipment fabrication & maintenance'],
            ['OrionQG','QG exploration & survey mission planner'],
            ['TitanOpsQG','Heavy QG computation infrastructure'],
            ['NexusBaseQG','Multi-lab QG coordination hub officer'],
            ['BaseGuardQG','QG facility operations & security mgr'],
            ['FieldTeamQG','QG field experiment logistics coord'],
            ['SafeOneQG','QG safety protocol enforcement officer'],
            ['DataAlphaQG','QG secure data management specialist'],
            ['TrainCmdQG','QG agent training & development lead'],
            ['MedOpsQG','QG health & environment monitor'],
            ['CommsCtrQG','QG communications coordination officer'],
            ['SupplyQG','QG equipment & resource logistics'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 2: VACUUM ENERGY — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'vacuum_energy' => [
        'Theoretical Research' => [
            ['VacPolar','Vacuum polarization tensor & loop corrections'],
            ['PairForge','Schwinger pair production rate calculation'],
            ['FalseVac','False vacuum decay rate computation'],
            ['VacBubble','Vacuum bubble nucleation dynamics theory'],
            ['DiracSeaX','Extended Dirac sea electron-positron modeling'],
            ['ZPFTheory','Zero-point field statistical mechanics'],
            ['VacCondense','Vacuum condensate characterization theory'],
            ['CosmoLambda','Cosmological constant computation methods'],
            ['VacSymBreak','Vacuum symmetry breaking pattern analysis'],
            ['VacPhase','Vacuum phase transition order parameters'],
            ['RunningVac','Running vacuum energy scale dependence'],
            ['DeSitterVac','De Sitter vacuum state characterization'],
            ['VacEntropy','Vacuum entropy & information content theory'],
            ['VacThermal','Thermal vacuum effect finite-temp modeling'],
            ['VacTopolog','Topological vacuum structure & theta terms'],
        ],
        'Experimental Science' => [
            ['NanoCasimir','Nanoscale Casimir force precision measurement'],
            ['MicroCavVac','Microwave cavity vacuum fluctuation tests'],
            ['PiezoForce','Piezoelectric vacuum force detection system'],
            ['PhotonCntV','Single vacuum photon counting experiments'],
            ['PlateGap','Critical plate gap Casimir measurements'],
            ['WedgeAngle','Wedge geometry vacuum force experiments'],
            ['CylCasimir','Cylindrical Casimir configuration testing'],
            ['SpherePlate','Sphere-plate Casimir force measurement'],
            ['VacBirefr','Vacuum birefringence detection in B-field'],
            ['MotionCas','Motional Casimir photon creation tests'],
            ['VacFrictn','Quantum vacuum friction sensing apparatus'],
            ['PulseVacEx','Pulsed vacuum field induced effects'],
            ['CasimirTrq','Casimir torque angular measurement'],
            ['VacNoiseQ','Quantum vacuum noise spectroscopy'],
            ['CritField','Near-Schwinger critical field experiments'],
        ],
        'Applied Engineering' => [
            ['RectennaVE','Rectenna vacuum energy harvesting arrays'],
            ['VacExtract','Vacuum energy extraction system prototype'],
            ['FluxCapture','Quantum flux capture & storage device'],
            ['FieldTapVE','Electromagnetic field energy tapping tech'],
            ['VacReactorX','Vacuum energy reactor core prototype'],
            ['ZPEModule','Zero-point energy cell module design'],
            ['NanoTapVE','Nanoscale vacuum energy harvesting mesh'],
            ['VacConvert','Vacuum-to-electrical conversion system'],
            ['VacAmplify','Vacuum energy signal amplification chain'],
            ['CasDrive','Casimir force micro-drive actuator'],
            ['VacPipelin','Vacuum energy transmission conduit design'],
            ['VacStoreU','Vacuum energy storage capacitor bank'],
            ['ScaleUpVE','Industrial-scale VE extraction scaling'],
            ['VacGridInt','Vacuum energy power grid integration'],
            ['MicroGenVE','Micro-generator vacuum energy cell fab'],
        ],
        'Computational Physics' => [
            ['QEDPrecise','Precision QED higher-order loop calculation'],
            ['CasimirSim','Casimir force finite-element simulation'],
            ['ModeSumVE','Electromagnetic mode summation algorithms'],
            ['ZetaRegVE','Zeta function regularization computation'],
            ['VacRenormC','Vacuum energy renormalization scheme code'],
            ['GreenCalcV','Green function vacuum state calculator'],
            ['PropagSimV','Feynman propagator simulation engine'],
            ['FieldQuantC','Field quantization numerical framework'],
            ['DensityMapV','Vacuum energy density field mapper'],
            ['WorldCalcV','Worldline numerical methods for Casimir'],
            ['HeatExpand','Heat kernel asymptotic expansion solver'],
            ['MultiBodyV','Multi-body Casimir interaction solver'],
            ['TempVacSim','Finite-temperature vacuum effects sim'],
            ['GeomCalcV','Geometry-dependent vacuum energy solver'],
            ['VacOptimiz','Vacuum extraction efficiency optimizer'],
        ],
        'Intelligence Operations' => [
            ['VacWatcher','Global vacuum energy research surveillance'],
            ['PatentScan','ZPE patent & application trend scanning'],
            ['NexusVacI','Cross-program vacuum energy intelligence'],
            ['VaultVacI','Classified vacuum research data analysis'],
            ['DeepDigVac','Deep ZPE literature & archive excavation'],
            ['PatternVac','Vacuum energy research pattern recognition'],
            ['TrendVacI','ZPE technology trajectory trend analysis'],
            ['InsightVac','Discovery & breakthrough identification'],
            ['ShadowVacI','Competitor vacuum energy monitoring post'],
            ['AlertVacI','ZPE breakthrough notification system'],
            ['CipherVacI','Encrypted vacuum research communication'],
            ['ProphetVac','Vacuum energy technology forecasting'],
            ['GuardVacI','Vacuum energy IP protection analyst'],
            ['ReviveVac','Forgotten ZPE experiment reanalysis'],
            ['GhostVacI','Stealth vacuum intelligence gathering'],
        ],
        'Field Operations' => [
            ['AthenaVE','VE division strategic planning officer'],
            ['HermesVE','Rapid VE lab deployment coordinator'],
            ['PrecisionVE','VE equipment precision calibration lead'],
            ['VulcanVE','VE equipment fabrication & maintenance'],
            ['ExploreVE','New VE experiment logistics setup coord'],
            ['TitanOpsVE','Heavy VE systems & infrastructure mgr'],
            ['HubVE','VE multi-lab coordination hub officer'],
            ['BaseVE','VE facility operations management'],
            ['FieldLabVE','Mobile VE lab operations coordinator'],
            ['SafetyVE','VE safety & hazard protocol enforcer'],
            ['DataVE','VE secure data handling specialist'],
            ['TrainVE','VE researcher onboarding & training'],
            ['MedLabVE','VE lab safety & exposure monitoring'],
            ['CommsVE','VE division communications officer'],
            ['SupplyVE','VE equipment procurement & logistics'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 3: WARP PHYSICS — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'warp_physics' => [
        'Theoretical Research' => [
            ['MetricDesn','Custom warp metric tensor design theory'],
            ['BubbleDyn','Warp bubble formation & stability dynamics'],
            ['SolitonWrp','Soliton-based FTL warp drive solutions'],
            ['EnergyBound','Quantum energy inequality bounds for warp'],
            ['CausalWarp','Causal structure preservation in warp'],
            ['GeodesicW','Geodesic behavior inside warp bubbles'],
            ['TidalWarp','Tidal force gradients in warp transitions'],
            ['StableWarp','Warp bubble dynamical stability analysis'],
            ['RadiatWarp','Hawking-like radiation from warp bubble'],
            ['SuperlumTh','Superluminal thermodynamics & arrow of time'],
            ['VanDenBrk','Volume-reduction warp metric variations'],
            ['WhiteWarp','Harold White optimized warp geometry'],
            ['PassengerPh','Passenger physics in FTL travel frame'],
            ['WarpSignat','Observable astrophysical warp signatures'],
            ['WarpParadox','FTL temporal paradox resolution theory'],
        ],
        'Experimental Science' => [
            ['BubbleDetct','Micro-warp bubble interferometric detection'],
            ['FieldGenWrp','Laboratory warp field generation attempts'],
            ['InterferWrp','Interferometric spacetime distortion tests'],
            ['LaserWarpD','Laser-based warp field detection system'],
            ['CavityWrp','Resonant cavity warp effect experiments'],
            ['DielectWrp','High-K dielectric warp field testing'],
            ['SuperconWrp','Superconductor warp coupling experiments'],
            ['PlasmaWrp','Plasma-based warp field amplification test'],
            ['IonTrapWrp','Ion trap warp micro-field measurements'],
            ['EmDriveAnl','EM drive anomalous thrust replication'],
            ['MagnetWrp','Magnetic field warp interaction testing'],
            ['VacuumWrp','Vacuum-state warp metric experiments'],
            ['PhotWarp','Photonic warp detection interferometry'],
            ['NegEnergyD','Squeezed-state negative energy measurement'],
            ['SpaceSensr','Laser ranging spatial metric change detect'],
        ],
        'Applied Engineering' => [
            ['DriveForge','Warp drive propulsion core engineering'],
            ['BubbleGen','Warp bubble field generator prototype'],
            ['FieldCoilW','Warp field generation coil system design'],
            ['NavWarp','FTL navigation coordinate system design'],
            ['HullWarp','Warp vessel hull stress engineering'],
            ['ContainWrp','Warp field containment barrier design'],
            ['StabilizeW','Bubble stabilization feedback loop system'],
            ['PowerWarp','Warp drive power delivery engineering'],
            ['CoolWarp','Warp system thermal management design'],
            ['ShieldWarp','Particle radiation shield during warp'],
            ['DropOutSys','Warp exit transition system engineering'],
            ['EntryProto','Warp bubble formation protocol system'],
            ['SafetyWrp','Warp field safety interlock system design'],
            ['ScaleWarp','Warp field scaling from micro to macro'],
            ['ProtoWarp','Full-scale warp prototype integration'],
        ],
        'Computational Physics' => [
            ['BubbleSim','Warp bubble spacetime evolution simulator'],
            ['MetricSolv','Warp spacetime metric numerical solver'],
            ['GRCalcWarp','General relativity field equation solver'],
            ['StressCalc','Stress-energy tensor computation engine'],
            ['TrajCalcW','Warp trajectory & optimal path calculator'],
            ['EnergyOptW','Warp energy budget optimization system'],
            ['StabilSim','Bubble stability perturbation simulator'],
            ['RadSimWarp','Warp radiation emission spectrum simulator'],
            ['CausalSimW','Warp causal structure evolution simulator'],
            ['WarpVisual','3D warp field visualization renderer'],
            ['ParticleW','Particle physics in warp background sim'],
            ['QuantumWrp','Quantum effects in warp field computation'],
            ['ThermoWarp','Thermodynamic warp analysis calculation'],
            ['GeodCalcW','Geodesic deviation in warp calculator'],
            ['HorizonSim','Apparent horizon formation simulator'],
        ],
        'Intelligence Operations' => [
            ['WarpWatch','Global warp drive research surveillance'],
            ['PropulScan','Advanced propulsion patent monitoring'],
            ['NexusWarpI','Cross-program warp tech intelligence'],
            ['VaultWarpI','Classified warp research data analysis'],
            ['DeepWarpI','Deep warp physics literature excavation'],
            ['PatternWrI','Warp research pattern & trend analysis'],
            ['TrendWarpI','Warp technology trajectory prediction'],
            ['InsightWrI','Warp breakthrough identification agent'],
            ['ShadowWrpI','Competitor warp research monitoring'],
            ['AlertWarpI','Warp tech breakthrough alert system'],
            ['CipherWrpI','Encrypted warp intelligence processing'],
            ['ProphetWrI','Warp technology timeline forecasting'],
            ['GuardWarpI','Warp technology IP protection analyst'],
            ['ReviveWrpI','Failed warp experiment rehydration'],
            ['GhostWarpI','Stealth warp intelligence operations'],
        ],
        'Field Operations' => [
            ['AthenaWP','Warp division strategic planning officer'],
            ['HermesWP','Rapid warp equipment deployment coord'],
            ['PrecisionWP','Warp equipment calibration specialist'],
            ['VulcanWP','Warp equipment fabrication & machining'],
            ['ExploreWP','Warp experiment site logistics manager'],
            ['TitanOpsWP','Heavy warp test infrastructure manager'],
            ['HubWP','Warp multi-site coordination hub officer'],
            ['BaseWP','Warp test facility operations manager'],
            ['FieldWP','Warp field test operations coordinator'],
            ['SafetyWP','Warp field safety protocol enforcer'],
            ['DataWP','Warp secure data management specialist'],
            ['TrainWP','Warp experiment team training officer'],
            ['MedWP','Warp field exposure health monitor'],
            ['CommsWP','Warp division communications officer'],
            ['SupplyWP','Warp parts & materials procurement'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 4: ANTIGRAVITY — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'antigravity' => [
        'Theoretical Research' => [
            ['ElectroGrv','Electrogravitics field theory development'],
            ['GravitoEM','Gravitoelectromagnetic coupling analysis'],
            ['CooperGrav','Cooper pair gravitational interaction theory'],
            ['LatticeGrv','Ion lattice gravitomagnetic moment theory'],
            ['QuantumLift','Quantum mechanical lift force derivation'],
            ['DielectGrv','High-K dielectric gravity coupling theory'],
            ['MachThry','Extended Mach effect thrust formulation'],
            ['PushGravit','Push-down gravity from vacuum hypothesis'],
            ['VacLift','Vacuum-mediated lift force mechanisms'],
            ['InertiaZPF','Inertia as ZPF interaction Haisch theory'],
            ['GravShldTh','Gravitational shielding theoretical limits'],
            ['NegMassTh','Negative mass dynamics & stability theory'],
            ['DipoleGrTh','Gravitational dipole drive theory'],
            ['RotorGravTh','Rotating mass gravity anomaly theory'],
            ['BulkForce','Bulk force manipulation via field coupling'],
        ],
        'Experimental Science' => [
            ['SpinDiscEx','Spinning superconductor disc experiments'],
            ['HighVoltGrv','High-voltage gravitational anomaly tests'],
            ['CryoRotor','Cryogenic rotor angular momentum tests'],
            ['PlasmaLift','Plasma confinement lift experiments'],
            ['GyroAnomal','Precision gyroscope anomaly detection'],
            ['PendulumAG','Pendulum AG shielding sensitivity tests'],
            ['CapacitorAG','Asymmetric capacitor thrust measurement'],
            ['MagLevQ','Quantum-enhanced magnetic levitation'],
            ['SpinTorque','Gravitomagnetic spin torque detection'],
            ['LaserWeigh','Laser interferometric weight change test'],
            ['VacLiftExp','Vacuum interaction lift experiments'],
            ['PiezoGravX','Piezo gravitational anomaly measurement'],
            ['AcoustLift','Acoustic levitation enhancement research'],
            ['RotFieldAG','Rotating EM field gravity coupling tests'],
            ['ThermalAG','Thermal gradient gravitational anomaly'],
        ],
        'Applied Engineering' => [
            ['LiftEngine','Anti-gravity lift engine core design'],
            ['HoverPad','Hover platform chassis engineering'],
            ['ShieldDome','Gravity shield dome field generator'],
            ['InertDampr','Inertial dampener feedback loop system'],
            ['ThrustCore','Reactionless thrust engine prototype'],
            ['FieldPlate','Gravity field plate array fabrication'],
            ['CoilStackAG','Superconductor coil stack assembly'],
            ['RotorDrive','Rotating mass drive engineering'],
            ['VoltLift','High-voltage lift system construction'],
            ['DielectStk','Multi-layer dielectric stack thruster'],
            ['GravBatter','Gravitational potential energy storage'],
            ['SteerGrav','Gravitational vector steering mechanism'],
            ['VertCtrl','Vertical thrust & hover control system'],
            ['ScaleAGSys','Industrial-scale AG system engineering'],
            ['ProtoPlatf','AG prototype test platform build lead'],
        ],
        'Computational Physics' => [
            ['LiftSimAG','Anti-gravity lift force simulation'],
            ['FieldMapAG','Gravity field mapping & visualization'],
            ['FEMGravAG','Finite element gravity model analysis'],
            ['CooperSimA','Cooper pair gravitational sim engine'],
            ['EMGravSim','EM-gravity coupling field simulator'],
            ['RotDynSim','Rotor dynamics gravitomagnetic sim'],
            ['InerCalcAG','Inertia modification effect calculator'],
            ['ShieldSimAG','Gravity shield effectiveness simulator'],
            ['ThrustCalcA','Reactionless thrust prediction engine'],
            ['MatSimAG','Material response to AG fields sim'],
            ['VacCoupSim','Vacuum-matter coupling calculator'],
            ['MachCalcAG','Mach effect thrust prediction model'],
            ['DipoleSimAG','Gravitational dipole field simulator'],
            ['ScaleSimAG','AG system scaling analysis engine'],
            ['OptimAG','AG device geometry optimizer'],
        ],
        'Intelligence Operations' => [
            ['AGWatch','Anti-gravity technology surveillance'],
            ['AGPatent','AG patent & disclosure monitoring'],
            ['NexusAGI','Cross-program AG tech intelligence'],
            ['VaultAGI','Classified AG research data analysis'],
            ['DeepAGI','Deep AG literature & archive mining'],
            ['PatternAGI','AG research pattern identification'],
            ['TrendAGI','AG technology development trend tracking'],
            ['InsightAGI','AG breakthrough detection specialist'],
            ['ShadowAGI','Competitor AG program monitoring'],
            ['AlertAGI','AG technology breakthrough alerts'],
            ['CipherAGI','Encrypted AG intelligence processing'],
            ['ProphetAGI','AG technology timeline forecasting'],
            ['GuardAGI','AG intellectual property protection'],
            ['ReviveAGI','Historical AG experiment reanalysis'],
            ['GhostAGI','Stealth AG intelligence operations'],
        ],
        'Field Operations' => [
            ['AthenaAG','AG division strategic planning officer'],
            ['HermesAG','Rapid AG deployment coordinator'],
            ['PrecisionAG','AG equipment calibration specialist'],
            ['VulcanAG','AG equipment fabrication specialist'],
            ['ExploreAG','AG field experiment logistics coord'],
            ['TitanOpsAG','Heavy AG test infrastructure manager'],
            ['HubAG','AG multi-site coordination hub officer'],
            ['BaseAG','AG facility operations manager'],
            ['FieldAG','AG field operations coordinator'],
            ['SafetyAG','AG field safety protocol enforcer'],
            ['DataAG','AG secure data management specialist'],
            ['TrainAG','AG researcher training & dev lead'],
            ['MedAG','AG field exposure health monitor'],
            ['CommsAG','AG division communications officer'],
            ['SupplyAG','AG equipment & parts procurement'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 5: CONSCIOUSNESS — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'consciousness' => [
        'Theoretical Research' => [
            ['QuantMind','Quantum mind formal theory development'],
            ['PhiSpace','Integrated information Φ space geometry'],
            ['PanPsych','Panpsychism formal logic & ontology'],
            ['OrchORExt','Orchestrated OR microtubule extension'],
            ['QuantCogni','Quantum cognition decision model theory'],
            ['ConsCollps','Consciousness-collapse mechanism theory'],
            ['NeuroBind','Neural binding quantum coherence theory'],
            ['FreeWillQ','Quantum indeterminacy & free will models'],
            ['QuantInten','Quantum intentionality formal framework'],
            ['MicroTubeQ','Microtubule quantum vibration theory'],
            ['ConsEmerg','Consciousness emergence phase transition'],
            ['SubjExpTh','Subjective experience formal ontology'],
            ['QuantPerc','Quantum perception & measurement theory'],
            ['ConsEntangl','Consciousness-entanglement coupling model'],
            ['UnitaryMnd','Unitary consciousness field hypothesis'],
        ],
        'Experimental Science' => [
            ['EEGQuantum','EEG quantum coherence signature detection'],
            ['NeuroPhiEx','Neural Φ measurement experimental protocol'],
            ['MicroScanC','Microtubule coherence time scanning'],
            ['ConsMetric','Consciousness metric instrument design'],
            ['BindingExp','Neural binding synchrony experiments'],
            ['FreeChocQ','Quantum random choice timing experiments'],
            ['IntentDtct','Directed intention detection testing'],
            ['AwareProbe','Awareness level boundary probing tests'],
            ['LucidState','Lucid dreaming induction & EEG analysis'],
            ['PlaceboQ','Quantum observer placebo effect research'],
            ['PsiTestCtl','Controlled PSI phenomena experimentation'],
            ['MeditateQ','Meditation quantum correlation measurement'],
            ['AnesthBndr','Anesthesia consciousness boundary testing'],
            ['SplitBrain','Split-brain consciousness duality tests'],
            ['DreamQuant','Dream state quantum signature analysis'],
        ],
        'Applied Engineering' => [
            ['ConsInterf','Brain-computer consciousness interface'],
            ['NeuralAmpC','Neural quantum signal amplification sys'],
            ['PhiDetectr','Integrated information meter instrument'],
            ['MindLinkDv','Mind-machine quantum bridge prototype'],
            ['ConsBoost','Consciousness enhancement field device'],
            ['TubeStim','Microtubule coherence stimulation device'],
            ['FieldHelmt','Consciousness field detection helmet'],
            ['EmotSense','Quantum emotion detection sensor array'],
            ['ThoughtCst','Thought pattern broadcast transmitter'],
            ['AwareLvl','Awareness depth level indicator device'],
            ['DreamRecrd','Dream state recording & playback device'],
            ['ConsShield','Consciousness protection field device'],
            ['TelePresQ','Quantum telepresence prototype system'],
            ['IntentAmpC','Quantum intention amplifier prototype'],
            ['NeurMapDev','Full-brain neural quantum mapping device'],
        ],
        'Computational Physics' => [
            ['PhiCalcC','Integrated information Φ computation'],
            ['NeuralSimC','Neural quantum dynamics simulator'],
            ['ConsSimEng','Consciousness substrate simulation'],
            ['MicroModlC','Microtubule quantum coherence model'],
            ['BindCalcC','Binding problem computational solution'],
            ['FreeWillSm','Free will quantum simulation engine'],
            ['IntentModl','Intention field computational model'],
            ['AwareCalcC','Awareness level prediction calculator'],
            ['QuantBrain','Full quantum brain dynamics simulation'],
            ['EntropyMnd','Consciousness entropy flow computation'],
            ['CoherSimC','Neural coherence field simulator'],
            ['NetConsC','Consciousness network topology model'],
            ['InfoIntegC','Information integration rate calculator'],
            ['WaveMindC','Mind-wave function evolution model'],
            ['QuantCogSm','Quantum cognition behavior simulator'],
        ],
        'Intelligence Operations' => [
            ['MindWatch','Consciousness research global monitoring'],
            ['NeuroPat','Neuroscience patent & paper surveillance'],
            ['NexusMindI','Cross-program consciousness intelligence'],
            ['VaultMindI','Classified consciousness research intel'],
            ['DeepMindI','Deep consciousness literature excavation'],
            ['PtrnMindI','Consciousness research pattern analysis'],
            ['TrendMindI','Neuroscience trend trajectory tracking'],
            ['InsightMnI','Consciousness breakthrough identification'],
            ['ShadwMindI','Competitor consciousness program monitoring'],
            ['AlertMindI','Consciousness breakthrough notification'],
            ['CipherMndI','Encrypted consciousness intel processing'],
            ['PrphtMindI','Consciousness technology forecasting'],
            ['GuardMindI','Consciousness research IP protection'],
            ['RevivMindI','Historical consciousness experiment review'],
            ['GhostMindI','Stealth consciousness intel gathering'],
        ],
        'Field Operations' => [
            ['AthenaCons','Consciousness strategic planning officer'],
            ['HermesCons','Rapid experiment deployment coordinator'],
            ['PrecsnCons','Consciousness equipment calibration'],
            ['VulcanCons','Consciousness instrument fabrication'],
            ['ExplrCons','Consciousness field study logistics'],
            ['TitanCons','Heavy consciousness infrastructure mgr'],
            ['HubCons','Consciousness multi-lab coordination'],
            ['BaseCons','Consciousness facility operations mgr'],
            ['FieldCons','Consciousness field research coordinator'],
            ['SafetyCons','Consciousness ethics & safety officer'],
            ['DataCons','Consciousness data security specialist'],
            ['TrainCons','Consciousness researcher training lead'],
            ['MedCons','Consciousness researcher wellness monitor'],
            ['CommsCons','Consciousness division comms officer'],
            ['SupplyCons','Consciousness equipment procurement'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 6: TIME PHYSICS — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'time_physics' => [
        'Theoretical Research' => [
            ['TimeFlowTh','Flow of time formal mathematical theory'],
            ['CTCTheory','Closed timelike curve stability analysis'],
            ['ChronoProt','Chronology protection conjecture proofs'],
            ['TemporalQM','Temporal quantum mechanics formulation'],
            ['TimeSymmTh','Time reversal symmetry violation theory'],
            ['DurationQ','Quantum duration uncertainty relations'],
            ['TimeEmergQ','Time emergence from entanglement theory'],
            ['ClockParad','Twin paradox extreme relativistic cases'],
            ['TempSuper','Temporal superposition of causal order'],
            ['TimeOrder','Indefinite causal order formal theory'],
            ['ChronoFld','Temporal field theory Lagrangian design'],
            ['RetroSig','Retrocausal signaling no-go theorem study'],
            ['TimeBlockQ','Block universe quantum compatibility'],
            ['PreSentism','Presentism & quantum non-locality theory'],
            ['QuantDelay','Quantum delayed choice extension theory'],
        ],
        'Experimental Science' => [
            ['TimeDilate','Extreme time dilation precision testing'],
            ['CrystalGrw','Novel time crystal phase fabrication'],
            ['CausalOrdEx','Indefinite causal order lab experiments'],
            ['QuantSwitch','Quantum switch causal order lab setup'],
            ['RetroTestEx','Retrocausality detection experiments'],
            ['ClockPair','Entangled atomic clock pair measurement'],
            ['TimeRevBEC','Time-reversal invariance BEC experiments'],
            ['FloquetExp','Floquet time crystal creation & testing'],
            ['DurationMs','Duration measurement quantum limit test'],
            ['CPTTestEx','CPT symmetry high-precision testing'],
            ['TempGateEx','Temporal quantum gate implementation'],
            ['FreqQuantEx','Quantum frequency standard experiments'],
            ['SeqQuantEx','Quantum causal sequence testing'],
            ['TimeRefrac','Temporal refraction photonic experiments'],
            ['MemQuantEx','Quantum memory coherence lifetime tests'],
        ],
        'Applied Engineering' => [
            ['ChronoFrge','Temporal engineering fabrication lead'],
            ['CrystalCor','Time crystal core device engineering'],
            ['FloqEngine','Floquet system driver circuit design'],
            ['TempGateEn','Temporal gate circuit engineering'],
            ['TimeLensEn','Temporal lens dispersion engineering'],
            ['TimeBuffer','Temporal pulse buffer system design'],
            ['DuraCtrl','Duration control feedback loop system'],
            ['FreqEngTm','Frequency synthesis engineering system'],
            ['TimeShift','Time-rate shift prototype engineering'],
            ['DelayLineQ','Quantum delay line waveguide engineering'],
            ['ChronoShld','Temporal shielding prototype system'],
            ['TempNavSys','Temporal navigation coordinate system'],
            ['ClockForge','Ultra-precision clock engineering'],
            ['PulseTimEn','Temporal pulse generation engineering'],
            ['TimeStoreD','Temporal state storage device design'],
        ],
        'Computational Physics' => [
            ['ChronoSim','Temporal dynamics evolution simulator'],
            ['CTCSolver','CTC trajectory self-consistency solver'],
            ['FloqCalc','Floquet quasi-energy spectrum calculator'],
            ['TimeEvolve','Quantum time evolution algorithm'],
            ['CausalCalcT','Causal structure evolution computation'],
            ['RetroSimT','Retrocausality model simulator'],
            ['TCrystSim','Time crystal phase diagram simulator'],
            ['ArrowCalcT','Arrow of time entropy flow calculator'],
            ['EntrpTimSm','Entropy-time correlation analyzer'],
            ['TempOptim','Temporal operation sequence optimizer'],
            ['OrderCalcT','Causal order computation engine'],
            ['DuraSimT','Duration quantum simulation engine'],
            ['FreqSimT','Frequency domain temporal simulator'],
            ['PhaseCalcT','Temporal phase evolution calculator'],
            ['ChroModelT','Full chronodynamics numerical model'],
        ],
        'Intelligence Operations' => [
            ['TimeWatchI','Time physics research global monitoring'],
            ['ChronoScan','Temporal tech patent surveillance agent'],
            ['NexusTimeI','Cross-program temporal theory intelligence'],
            ['VaultTimeI','Classified temporal research data intel'],
            ['DeepTimeI','Deep temporal physics literature mining'],
            ['PtrnTimeI','Time physics research pattern detection'],
            ['TrendTimeI','Temporal technology trend tracking agent'],
            ['InsightTmI','Temporal breakthrough identification'],
            ['ShadwTimeI','Competitor time research monitoring'],
            ['AlertTimeI','Temporal breakthrough notification sys'],
            ['CipherTmI','Encrypted temporal intel processing'],
            ['PrphtTimeI','Temporal technology timeline forecasting'],
            ['GuardTimeI','Temporal research IP & asset protection'],
            ['RevivTimeI','Historical time experiment reanalysis'],
            ['GhostTimeI','Stealth temporal intelligence gathering'],
        ],
        'Field Operations' => [
            ['AthenaTP','Time physics strategic planning officer'],
            ['HermesTP','Rapid temporal equipment deployment'],
            ['PrecisionTP','Temporal equipment calibration lead'],
            ['VulcanTP','Temporal equipment fabrication specialist'],
            ['ExploreTP','Temporal experiment logistics coordinator'],
            ['TitanOpsTP','Heavy temporal infrastructure manager'],
            ['HubTP','Temporal multi-lab coordination officer'],
            ['BaseTP','Temporal facility operations manager'],
            ['FieldTP','Temporal field operations coordinator'],
            ['SafetyTP','Temporal safety protocol enforcer'],
            ['DataTP','Temporal secure data management'],
            ['TrainTP','Temporal team training & development'],
            ['MedTP','Temporal exposure health monitor'],
            ['CommsTP','Temporal division communications officer'],
            ['SupplyTP','Temporal equipment & parts procurement'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 7: DIMENSIONAL PHYSICS — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'dimensional' => [
        'Theoretical Research' => [
            ['CompactDim','Compactification topology & moduli theory'],
            ['WarpedDim','Warped extra dimension geometry analysis'],
            ['LargeXtra','Large extra dimension ADD model theory'],
            ['BraneWorld','Braneworld cosmology & phenomenology'],
            ['StringLand','String landscape & vacuum statistics'],
            ['ModuliStab','Moduli field stabilization mechanisms'],
            ['FoldedSpc','Folded dimension hidden sector theory'],
            ['DimTunnelT','Dimensional tunneling probability theory'],
            ['BulkGravit','Graviton propagation in bulk spacetime'],
            ['MirrorMatr','Mirror matter on parallel brane theory'],
            ['KKTowerTh','Kaluza-Klein mass tower phenomenology'],
            ['DimDecomp','Dimensional decomposition at high energy'],
            ['HiddenDimS','Hidden dimension experimental signatures'],
            ['EkpyroticT','Ekpyrotic brane collision cosmology'],
            ['ParallelUT','Parallel universe quantum branching theory'],
        ],
        'Experimental Science' => [
            ['DimProbeEx','Extra dimension probing at colliders'],
            ['GravLeakex','Gravitational leakage detection at sub-mm'],
            ['KKDetectEx','Kaluza-Klein mode particle detection'],
            ['BulkSignal','Bulk particle production signal search'],
            ['MicroGravD','Microscale gravity inverse-square test'],
            ['ColliderDm','Collider missing energy dimension search'],
            ['TableDimEx','Tabletop extra dimension detection tests'],
            ['GravRangeD','Short-range gravity deviation experiments'],
            ['InvSqrTst','Newton inverse square law precision test'],
            ['DimPairPrd','Extra dimension pair production search'],
            ['TorsionDim','Torsion balance sub-mm gravity testing'],
            ['NeutronDim','Neutron mirror world oscillation tests'],
            ['PhotonDimX','Photon disappearance dimension signature'],
            ['CosmicDimS','Cosmic ray extra dimension anomalies'],
            ['MagneticDm','Magnetic field dimension coupling tests'],
        ],
        'Applied Engineering' => [
            ['DimGateEng','Dimensional gateway device engineering'],
            ['PortalFrm','Portal stabilization frame construction'],
            ['BulkAccess','Bulk space access probe engineering'],
            ['FoldEngine','Space fold engine prototype design'],
            ['DimBridge','Inter-dimensional bridge technology'],
            ['CompactCor','Compactification core field device'],
            ['ExtraDoor','Extra dimension door coupling device'],
            ['DimStab','Dimensional stability control system'],
            ['GateFieldG','Gateway field generator engineering'],
            ['TransDimEn','Trans-dimensional transport prototype'],
            ['DimShieldE','Dimensional breach shielding system'],
            ['BulkAntEng','Bulk space communication antenna system'],
            ['FoldNavEng','Fold navigation guidance engineering'],
            ['DimBeaconE','Dimensional beacon locator device'],
            ['PortalPwrE','Portal power supply system design'],
        ],
        'Computational Physics' => [
            ['DimSimComp','Extra dimension field simulation engine'],
            ['StringSimC','String theory vacuum simulation code'],
            ['BraneSimC','Brane dynamics evolution simulator'],
            ['ModuliCalc','Moduli space potential landscape calc'],
            ['KKSpecCalc','KK mode spectrum mass calculation'],
            ['LndscpSimC','String landscape statistical simulator'],
            ['CmpctCalcC','Compactification geometry calculator'],
            ['BulkSimDim','Bulk propagation numerical simulator'],
            ['DimTopoSim','Dimension topology change simulator'],
            ['MirrorCalc','Mirror matter production rate calculator'],
            ['FoldCalcDm','Space fold energy requirement calculator'],
            ['DimEnCalc','Dimensional energy barrier computation'],
            ['PortalSim','Portal stability dynamics simulator'],
            ['WrpDimCalc','Warped dimension graviton propagation calc'],
            ['MultiSimDm','Multiverse branching probability simulator'],
        ],
        'Intelligence Operations' => [
            ['DimWatchI','Dimensional physics research surveillance'],
            ['DimScanI','Extra dimension patent & paper scanning'],
            ['NexusDimI','Cross-program dimensional intelligence'],
            ['VaultDimI','Classified dimensional research intel'],
            ['DeepDimI','Deep dimensional literature excavation'],
            ['PtrnDimI','Dimensional research pattern analysis'],
            ['TrendDimI','Dimensional tech trajectory tracking'],
            ['InsightDmI','Dimensional breakthrough identification'],
            ['ShadwDimI','Competitor dimensional research monitor'],
            ['AlertDimI','Dimensional breakthrough alert system'],
            ['CipherDmI','Encrypted dimensional intel processing'],
            ['PrphtDimI','Dimensional technology forecasting'],
            ['GuardDimI','Dimensional research IP protection'],
            ['RevivDimI','Historical dimension experiment review'],
            ['GhostDimI','Stealth dimensional intelligence ops'],
        ],
        'Field Operations' => [
            ['AthenaDim','Dimensional strategic planning officer'],
            ['HermesDim','Rapid dimensional deployment coordinator'],
            ['PrecsnDim','Dimensional equipment calibration lead'],
            ['VulcanDim','Dimensional equipment fabrication lead'],
            ['ExplrDim','Dimensional experiment logistics coord'],
            ['TitanDim','Heavy dimensional infrastructure mgr'],
            ['HubDim','Dimensional multi-lab coordination hub'],
            ['BaseDim','Dimensional facility operations manager'],
            ['FieldDim','Dimensional field operations coordinator'],
            ['SafetyDim','Dimensional safety protocol enforcer'],
            ['DataDim','Dimensional secure data management'],
            ['TrainDim','Dimensional team training & development'],
            ['MedDim','Dimensional exposure health monitor'],
            ['CommsDim','Dimensional division communications'],
            ['SupplyDim','Dimensional equipment procurement'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 8: UAP ENGINEERING — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'uap_engineering' => [
        'Theoretical Research' => [
            ['PropulThry','UAP field propulsion dynamics theory'],
            ['FieldDriveT','Field-effect propulsion formal theory'],
            ['InertCancel','Inertial frame cancellation theory'],
            ['GravPropul','Gravitational propulsion theory models'],
            ['MHDLifter','MHD atmospheric lifter theory'],
            ['ElectKinet','Electrokinetic propulsion theory'],
            ['PlasSheath','Plasma sheath aerodynamic theory'],
            ['EMDriveThr','EM drive cavity thrust theory analysis'],
            ['MassReduce','Active mass reduction field theory'],
            ['ReactLess','Reactionless drive momentum theory'],
            ['AeroAnomly','Anomalous aerodynamic theory models'],
            ['RadarInvs','Plasma radar invisibility theory'],
            ['SilentProp','Silent field propulsion mechanism theory'],
            ['OceanSubTh','Trans-medium propulsion physics theory'],
            ['InstAccel','Instantaneous acceleration frame theory'],
        ],
        'Experimental Science' => [
            ['PropulTest','UAP propulsion anomaly testing lab'],
            ['FieldGenUA','Field propulsion generator experiments'],
            ['PlasmaTestU','Plasma sheath generation & testing'],
            ['MHDTestUA','MHD thruster performance testing'],
            ['InertTest','Inertia modification detection tests'],
            ['SilentTest','Silent operation verification testing'],
            ['RadarTestU','Radar cross-section testing chamber'],
            ['WaterTestU','Air-to-water transition testing'],
            ['AeroTestUA','Anomalous aerodynamic measurement'],
            ['AccelTestU','Extreme g-force acceleration testing'],
            ['MatTestUA','Advanced metamaterial testing lab'],
            ['EMFieldTst','EM field propulsion force measurement'],
            ['VacPropTst','Vacuum state propulsion force tests'],
            ['HoverTestU','Stable hover demonstration testing'],
            ['ObservTest','UAP observational data verification'],
        ],
        'Applied Engineering' => [
            ['HullForgeU','UAP hull geometry design engineering'],
            ['DriveCoreU','Field propulsion core module design'],
            ['PlasSysUA','Plasma envelope system engineering'],
            ['NavComplxU','UAP navigation & guidance system'],
            ['StealthSys','EM signature suppression engineering'],
            ['ShieldSysU','Particle & radiation shield design'],
            ['PowerPltUA','UAP compact power plant engineering'],
            ['LifeSuprtU','Occupant life support system design'],
            ['CtrlSurfUA','Adaptive flight control system design'],
            ['SensArrayU','Multi-spectrum sensor array design'],
            ['CommStlthU','Low-observable communications system'],
            ['LandSysUA','Variable-terrain landing gear system'],
            ['CockpitUA','Cockpit HUD & neural interface design'],
            ['MatHullUA','Advanced hull material composite design'],
            ['IntegSysUA','Full vehicle systems integration lead'],
        ],
        'Computational Physics' => [
            ['FlightSimU','UAP flight dynamics simulation engine'],
            ['PropulSimU','Field propulsion force simulation'],
            ['AeroCalcUA','UAP aerodynamic profile calculator'],
            ['FieldCalcU','Field propulsion strength computation'],
            ['PlasCalcUA','Plasma sheath dynamics simulation'],
            ['TrajCalcUA','UAP trajectory optimization engine'],
            ['StlthCalcU','Stealth RCS & signature calculator'],
            ['ThermCalcU','Thermal management simulation'],
            ['StructCalU','Structural stress & strain calculator'],
            ['PowerCalcU','Power budget & draw calculation sys'],
            ['SigCalcUA','Observable signature prediction calc'],
            ['MediumCalcU','Trans-medium transition phase sim'],
            ['AccelCalcU','Acceleration profile calculation'],
            ['ShieldCalU','Shield effectiveness prediction sim'],
            ['MissnPlanU','Mission profile planning optimizer'],
        ],
        'Intelligence Operations' => [
            ['UAPWatchI','Global UAP sighting & tech monitoring'],
            ['SightScanI','UAP sighting pattern analysis system'],
            ['NexusUAPI','Cross-program UAP tech intelligence'],
            ['VaultUAPI','Classified UAP materials & data intel'],
            ['DeepUAPI','Deep UAP historical literature mining'],
            ['PatternUAI','UAP flight pattern & behavior analysis'],
            ['TrendUAPI','UAP technology development trend tracking'],
            ['InsightUAI','UAP technology breakthrough identification'],
            ['ShadowUAI','Foreign UAP program monitoring post'],
            ['AlertUAPI','UAP encounter alert & dispatch system'],
            ['CipherUAPI','Encrypted UAP intelligence processing'],
            ['ProphtUAPI','UAP technology forecasting & prediction'],
            ['GuardUAPI','UAP technology IP & security protection'],
            ['RecoverUAI','UAP material recovery analysis team'],
            ['GhostUAPI','Stealth UAP intelligence field ops'],
        ],
        'Field Operations' => [
            ['AthenaUAP','UAP division strategic planning officer'],
            ['HermesUAP','Rapid UAP field team deployment coord'],
            ['PrecsnUAP','UAP equipment calibration specialist'],
            ['VulcanUAP','UAP prototype fabrication specialist'],
            ['ExplrUAP','UAP field expedition logistics manager'],
            ['TitanUAP','Heavy UAP test infrastructure manager'],
            ['HubUAP','UAP multi-site coordination hub officer'],
            ['BaseUAP','UAP test facility operations manager'],
            ['FieldUAP','UAP field recovery operations coord'],
            ['SafetyUAP','UAP exposure & safety protocol enforcer'],
            ['DataUAP','UAP secure data chain-of-custody mgr'],
            ['TrainUAP','UAP team training & simulation lead'],
            ['MedUAP','UAP encounter health effects monitor'],
            ['CommsUAP','UAP division secure communications'],
            ['SupplyUAP','UAP exotic materials procurement'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 9: TRANSMUTATION — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'transmutation' => [
        'Theoretical Research' => [
            ['NucMorph','Nuclear morphology & shell model theory'],
            ['TransmutQ','Quantum transmutation mechanism theory'],
            ['ColdFusnQ','LENR quantum tunneling enhancement theory'],
            ['LattNucTh','Lattice confinement fusion reaction theory'],
            ['PlasmNucQ','Plasma nuclear reaction dynamics theory'],
            ['PhotoNucTh','Photo-nuclear reaction cross-section theory'],
            ['NeutrCapTh','Enhanced neutron capture theory extensions'],
            ['ProtonChn','Proton chain catalytic optimization theory'],
            ['IsotopeShf','Isotope shift precision calculation theory'],
            ['MatrixCrt','Matrix element creation & annihilation theory'],
            ['ElemForge','Super-heavy element synthesis path theory'],
            ['NucAlchem','Modern nuclear alchemy atomic theory'],
            ['CrossSectT','Nuclear cross-section optimization theory'],
            ['CoulmbOver','Coulomb barrier tunnel enhancement theory'],
            ['QuantTunnN','Nuclear tunneling wavefunction engineering'],
        ],
        'Experimental Science' => [
            ['ColdFusnLb','LENR cold fusion replication experiments'],
            ['LattExpTR','Lattice confinement fusion verification'],
            ['PlasmNucEx','Plasma nuclear reaction experiments'],
            ['ElectrChm','Electrochemical nuclear loading tests'],
            ['GasLoadExp','Gas loading Pd-D2 experiments'],
            ['CathodeExp','Cathode sputtering nuclear tests'],
            ['IsoTracExp','Isotope tracing product analysis'],
            ['NeutCntExp','Neutron emission counting experiments'],
            ['ExcessHeat','Excess heat calorimetric measurement'],
            ['Helium4Det','Helium-4 correlated heat measurement'],
            ['TransTrace','Transmutation product trace analysis'],
            ['CavitNucEx','Sonoluminescence nuclear experiments'],
            ['LaserNucEx','Laser-induced nuclear reaction tests'],
            ['AcoustNuc','Acoustic stimulation nuclear testing'],
            ['BioTransEx','Biological transmutation verification'],
        ],
        'Applied Engineering' => [
            ['ReactForge','LENR reactor prototype engineering'],
            ['PlasmaChmb','Plasma reaction chamber design'],
            ['ElectrDesn','Advanced electrode design engineering'],
            ['LoadCellEn','Gas loading cell engineering system'],
            ['HeatCaptur','Heat capture & conversion engineering'],
            ['IsoRefine','Isotope enrichment system engineering'],
            ['NeutSource','Compact neutron source engineering'],
            ['ShieldNuc','Radiation shielding system engineering'],
            ['ContainNuc','Nuclear containment vessel design'],
            ['CalorimEng','Advanced calorimeter engineering'],
            ['VacChmbrEn','Ultra-high vacuum chamber engineering'],
            ['TargetFab','Nuclear target fabrication specialist'],
            ['DetectorEn','Radiation detector array engineering'],
            ['CtrlSysNuc','Nuclear process control system design'],
            ['WasteProc','Nuclear waste processing engineering'],
        ],
        'Computational Physics' => [
            ['NucSimTR','Nuclear reaction dynamics simulator'],
            ['LENRCalcTR','LENR reaction rate prediction calc'],
            ['CrossCalcN','Nuclear cross-section computation'],
            ['TunnelCalcN','Tunneling probability calculation engine'],
            ['LatticSimN','Lattice confinement dynamics simulator'],
            ['PlasmaSimN','Plasma nuclear interaction simulator'],
            ['IsoPopSim','Isotope population evolution simulator'],
            ['NeutrnSim','Neutron transport Monte Carlo simulator'],
            ['HeatCalcNu','Heat generation prediction calculator'],
            ['EnerBalanc','Nuclear energy balance computation'],
            ['DecayCalcN','Nuclear decay chain calculator'],
            ['BranchCalc','Branching ratio computation engine'],
            ['ResonCalcN','Nuclear resonance parameter calculator'],
            ['ScreenCalc','Electron screening potential calculator'],
            ['QMDSimTR','Quantum molecular dynamics simulator'],
        ],
        'Intelligence Operations' => [
            ['NucWatchI','Nuclear transmutation research monitoring'],
            ['LENRScanI','LENR patent & publication surveillance'],
            ['NexusNucI','Cross-program nuclear tech intelligence'],
            ['VaultNucI','Classified nuclear research data intel'],
            ['DeepNucI','Deep nuclear physics literature mining'],
            ['PtrnNucI','Nuclear research pattern recognition'],
            ['TrendNucI','Nuclear technology trend & trajectory'],
            ['InsightNcI','Nuclear breakthrough identification'],
            ['ShadwNucI','Competitor nuclear program monitoring'],
            ['AlertNucI','Nuclear discovery alert notification'],
            ['CipherNcI','Encrypted nuclear intel processing'],
            ['PrphtNucI','Nuclear technology forecasting agent'],
            ['GuardNucI','Nuclear technology IP protection analyst'],
            ['RevivNucI','Historical nuclear experiment reanalysis'],
            ['GhostNucI','Stealth nuclear intelligence operations'],
        ],
        'Field Operations' => [
            ['AthenaTR','Transmutation strategic planning officer'],
            ['HermesTR','Rapid nuclear deployment coordinator'],
            ['PrecsnTR','Nuclear equipment calibration specialist'],
            ['VulcanTR','Nuclear equipment fabrication specialist'],
            ['ExplrTR','Nuclear field experiment logistics coord'],
            ['TitanTR','Heavy nuclear infrastructure manager'],
            ['HubTR','Nuclear multi-lab coordination officer'],
            ['BaseTR','Nuclear facility operations manager'],
            ['FieldTR','Nuclear field operations coordinator'],
            ['SafetyTR','Nuclear safety & radiation protocol lead'],
            ['DataTR','Nuclear secure data management officer'],
            ['TrainTR','Nuclear team training & certification'],
            ['MedTR','Radiation exposure health monitoring'],
            ['CommsTR','Nuclear division communications officer'],
            ['SupplyTR','Nuclear materials procurement officer'],
        ],
    ],

    // ═══════════════════════════════════════════════════════
    // DIVISION 10: COSMIC ARCHITECTURE — 90 Specialists
    // ═══════════════════════════════════════════════════════
    'cosmic' => [
        'Theoretical Research' => [
            ['CosmicWeb','Large-scale cosmic web structure theory'],
            ['DarkFlowTh','Dark matter flow dynamics modeling'],
            ['DarkEnerX','Dark energy equation of state analysis'],
            ['CosmInflat','Inflationary cosmology scalar field theory'],
            ['MultiversQ','Multiverse probability measure theory'],
            ['CosmicStr','Cosmic string formation & dynamics'],
            ['BigBounce','Bouncing cosmology singularity avoidance'],
            ['CycCosmic','Cyclic Steinhardt-Turok cosmology theory'],
            ['HoloCosmic','Holographic cosmology boundary theory'],
            ['ConfCyclic','Conformal cyclic Penrose CCC cosmology'],
            ['TopDefect','Topological defect formation & evolution'],
            ['VoidCosm','Cosmic void dynamics & dark energy link'],
            ['PrimordFluc','Primordial quantum fluctuation seeding'],
            ['DarkSector','Dark sector coupling & portal theory'],
            ['FinalState','Cosmic eschatology & heat death theory'],
        ],
        'Experimental Science' => [
            ['CMBMapExp','CMB temperature & polarization analysis'],
            ['DarkDetExp','Dark matter direct detection experiments'],
            ['RedshftSrv','Galaxy redshift survey data analysis'],
            ['LensSurvey','Gravitational lensing survey analysis'],
            ['NeutrinoObs','Cosmic neutrino background observation'],
            ['GravWaveCo','Primordial gravitational wave detection'],
            ['BAOmeasure','Baryon acoustic oscillation measurement'],
            ['PolarCMBEx','CMB B-mode polarization experiment'],
            ['SNovaSurvey','Type Ia supernova luminosity survey'],
            ['GalaxySpin','Galaxy rotation curve precision analysis'],
            ['ClusterMas','Galaxy cluster mass weak lensing maps'],
            ['VoidSurvey','Cosmic void catalog & analysis'],
            ['QuasarSpec','High-z quasar spectrum analysis'],
            ['FilmntMap','Cosmic filament structure detection'],
            ['DarkRadio','Dark matter radio emission search'],
        ],
        'Applied Engineering' => [
            ['TelesForge','Next-gen telescope optical engineering'],
            ['DetectArrCo','Multi-wavelength detector array design'],
            ['SatDesignCo','Space observatory satellite engineering'],
            ['CryoDetCos','Cryogenic bolometer detector system'],
            ['ShieldCosmE','Cosmic ray shielding for deep space'],
            ['AntennaCosE','Radio telescope antenna array system'],
            ['OpticsFrge','Precision adaptive optics engineering'],
            ['FilterDesn','Spectral filter & grating engineering'],
            ['CalibSys','Photometric calibration system design'],
            ['DataPipeCo','Astronomy data pipeline engineering'],
            ['RemoteSenCo','Remote sensing satellite system eng'],
            ['SpacePlatCo','Space platform structural engineering'],
            ['AdaptOptEn','Adaptive optics wavefront correction'],
            ['CoronagEng','Coronagraph exoplanet imaging design'],
            ['InterferCo','Long-baseline interferometer engineering'],
        ],
        'Computational Physics' => [
            ['CosmoSimCo','Large-scale structure N-body simulation'],
            ['DarkMattSim','Dark matter halo formation simulation'],
            ['CMBCalcCo','CMB power spectrum analysis computation'],
            ['LensCalcCo','Gravitational lensing ray-tracing calc'],
            ['CosmoEvol','Cosmic evolution timeline simulator'],
            ['GalaxyForm','Galaxy formation hydrodynamic simulation'],
            ['ClusterSim','Galaxy cluster merger dynamics sim'],
            ['VoidSimCo','Cosmic void evolution simulation'],
            ['CosmStrSim','Cosmic string network evolution sim'],
            ['InflatCalcC','Inflationary model parameter calc'],
            ['BAOCalcCo','Baryon acoustic oscillation computation'],
            ['RedshftCalc','Photometric redshift estimation algo'],
            ['DarkCalcCo','Dark energy density evolution calc'],
            ['NBodyCosmos','Cosmological N-body gravity solver'],
            ['StatCosmos','Cosmic large-scale statistics analysis'],
        ],
        'Intelligence Operations' => [
            ['CosmWatchI','Cosmology research global surveillance'],
            ['AstroScanI','Astrophysics patent & paper monitoring'],
            ['NexusCosI','Cross-program cosmic theory intelligence'],
            ['VaultCosI','Classified cosmological research intel'],
            ['DeepCosI','Deep cosmology literature excavation'],
            ['PtrnCosI','Cosmological research pattern detection'],
            ['TrendCosI','Cosmology technology trend tracking'],
            ['InsightCoI','Cosmological breakthrough identification'],
            ['ShadwCosI','Competitor cosmology program review'],
            ['AlertCosI','Cosmology breakthrough alert system'],
            ['CipherCoI','Encrypted cosmology intel processing'],
            ['PrphtCosI','Cosmological technology forecasting'],
            ['GuardCosI','Cosmological research IP protection'],
            ['RevivCosI','Historical cosmology experiment review'],
            ['GhostCosI','Stealth cosmological intelligence ops'],
        ],
        'Field Operations' => [
            ['AthenaCos','Cosmic strategic planning officer'],
            ['HermesCos','Rapid cosmic deployment coordinator'],
            ['PrecsnCos','Cosmic equipment calibration lead'],
            ['VulcanCos','Cosmic instrument fabrication lead'],
            ['ExplrCos','Cosmic observation logistics coord'],
            ['TitanCos','Heavy cosmic infrastructure manager'],
            ['HubCos','Cosmic multi-site coordination hub'],
            ['BaseCos','Cosmic observatory operations manager'],
            ['FieldCos','Cosmic field observation coordinator'],
            ['SafetyCos','Cosmic exposure safety protocol lead'],
            ['DataCos','Cosmic secure data management lead'],
            ['TrainCos','Cosmic team training & development'],
            ['MedCos','Cosmic researcher health monitor'],
            ['CommsCos','Cosmic division communications officer'],
            ['SupplyCos','Cosmic equipment procurement officer'],
        ],
    ],

    ]; // end $data

    // Build agent array from structured data
    $agents = [];
    foreach ($data as $division => $corps) {
        $ti = 0;
        foreach ($corps as $corpName => $members) {
            $type = $types[$ti++];
            $ranks = $rankSets[$type];
            foreach ($members as $i => [$name, $spec]) {
                $agents[] = [
                    'name' => $name,
                    'division' => $division,
                    'role' => $corpName . ' — Genesis Specialist',
                    'specialty' => $spec,
                    'rank' => $ranks[$i] ?? 'Junior',
                    'tier' => 'specialist'
                ];
            }
        }
    }
    return $agents;
}
