<?php
/**
 * GoSiteMe language helper – syncs with billing portal language (en/fr; Hebrew uses English in WHMCS).
 * Use ?language=english or ?language=french to switch (or short ?lang=en|fr|he); preference is stored in cookie
 * and billing links get the same param so cart/client area open in the chosen language.
 */

if (!defined('GOSITEME_LANG_LOADED')) {
    define('GOSITEME_LANG_LOADED', 1);

    $GOSITEME_LANG_COOKIE = 'root_lang';
    $GOSITEME_LANG_COOKIE_DAYS = 365;
    $GOSITEME_LANG_EN = 'english';
    $GOSITEME_LANG_FR = 'french';
    $GOSITEME_LANG_HE = 'hebrew';

    // Resolve current language: GET (then set cookie and redirect) -> cookie -> default 'en'
    $requested = isset($_GET['language']) ? strtolower(trim($_GET['language'])) : '';
    // Short query alias (e.g. /about?lang=fr) — same cookie + redirect as ?language=french
    if ($requested === '' && isset($_GET['lang'])) {
        $short = strtolower(trim((string) $_GET['lang']));
        if ($short === 'fr') {
            $requested = 'french';
        } elseif ($short === 'en') {
            $requested = 'english';
        } elseif ($short === 'he') {
            $requested = 'hebrew';
        }
    }
    $root_is_https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || ((int) ($_SERVER['SERVER_PORT'] ?? 0) === 443)
        || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && strtolower((string) $_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https');
    $root_lang_cookie_opts = [
        'expires' => time() + $GOSITEME_LANG_COOKIE_DAYS * 86400,
        'path' => '/',
        // Secure-only cookies never persist on plain HTTP (local dev); follow actual TLS / proxy signal.
        'secure' => $root_is_https,
        'httponly' => true,
        'samesite' => 'Lax',
    ];

    if ($requested === 'fr' || $requested === 'french') {
        setcookie($GOSITEME_LANG_COOKIE, 'fr', $root_lang_cookie_opts);
        header('Location: ' . strtok($_SERVER['REQUEST_URI'] ?? '/', '?'), true, 302);
        exit;
    }
    if ($requested === 'en' || $requested === 'english') {
        setcookie($GOSITEME_LANG_COOKIE, 'en', $root_lang_cookie_opts);
        header('Location: ' . strtok($_SERVER['REQUEST_URI'] ?? '/', '?'), true, 302);
        exit;
    }
    if ($requested === 'he' || $requested === 'hebrew') {
        setcookie($GOSITEME_LANG_COOKIE, 'he', $root_lang_cookie_opts);
        header('Location: ' . strtok($_SERVER['REQUEST_URI'] ?? '/', '?'), true, 302);
        exit;
    }

    $current_lang = 'en';
    if (!empty($_COOKIE[$GOSITEME_LANG_COOKIE]) && in_array($_COOKIE[$GOSITEME_LANG_COOKIE], ['en', 'fr', 'he'], true)) {
        $current_lang = $_COOKIE[$GOSITEME_LANG_COOKIE];
    }

    // For billing: append ?language=english or &language=french to URLs (WHMCS has no Hebrew UI string pack here)
    function billing_lang_param() {
        global $current_lang, $GOSITEME_LANG_EN, $GOSITEME_LANG_FR;
        $billing_lang = ($current_lang === 'fr') ? $GOSITEME_LANG_FR : $GOSITEME_LANG_EN;
        return 'language=' . $billing_lang;
    }

    function billing_link($path) {
        $path = ltrim($path, '/');
        
        // Clean URL mapping — professional public-facing paths
        // URL path mappings for clean routing
        static $cleanMap = [
            // Authentication
            'login.php'            => '/login',
            'register.php'         => '/register',
            'clientarea.php'       => '/account',
            'index.php'            => '/login',
            // Shopping
            'cart.php'             => '/cart',
            // Support
            'contact.php'          => '/contact',
            'submitticket.php'     => '/submit-ticket',
            'supporttickets.php'   => '/support-tickets',
            'viewticket.php'       => '/view-ticket',
            'viewinvoice.php'      => '/view-invoice',
            'viewquote.php'        => '/view-quote',
            'viewemail.php'        => '/view-email',
            'serverstatus.php'     => '/server-status',
            // Content & resources
            'affiliates.php'       => '/affiliates',
            'knowledgebase.php'    => '/knowledgebase',
            'knowledgebase'        => '/knowledgebase',
            'announcements.php'    => '/announcements',
            'announcements'        => '/announcements',
            'announcementsrss.php' => '/announcements/rss',
            // Store — explicit mappings
            'store/ai-domain-hosting-connected-with-ai-editor' => '/store/hosting',
            'store/ssl-certificates'  => '/store/ssl',
            'store/token-packs'       => '/store/tokens',
            'store/training'          => '/store/training',
            'store/ai-server-support' => '/store/server-support',
            'store/ai-voice-agents'   => '/store/voice-agents',
            'store/domains-register'  => '/store/domains',
            'store/wordpress-hosting' => '/store/wordpress',
        ];
        
        // Split path from query string
        $pathOnly = strtok($path, '?');
        $query    = (strpos($path, '?') !== false) ? substr($path, strpos($path, '?')) : '';
        
        // Exact match in clean map
        if (isset($cleanMap[$pathOnly])) {
            $url = $cleanMap[$pathOnly];
            return $url . ($query ? $query . '&' : '?') . billing_lang_param();
        }
        
        // Store paths catch-all
        if (strpos($pathOnly, 'store/') === 0) {
            return '/' . $pathOnly . ($query ? $query . '&' : '?') . billing_lang_param();
        }
        
        // Fallback: clean root-relative URL
        // .htaccess rewrites these to billing portal endpoints
        return '/' . $path . (strpos($path, '?') !== false ? '&' : '?') . billing_lang_param();
    }

    /**
     * Same-document URL to switch UI language (?lang=) while preserving other query params.
     */
    function lang_switch_href($to) {
        $to = strtolower((string) $to);
        if (!in_array($to, ['en', 'fr', 'he'], true)) {
            $to = 'en';
        }
        $path = parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH);
        if ($path === null || $path === '' || $path === false) {
            $path = '/';
        }
        $q = [];
        if (!empty($_SERVER['QUERY_STRING'])) {
            parse_str($_SERVER['QUERY_STRING'], $q);
        }
        unset($q['lang'], $q['language']);
        $q['lang'] = $to;
        $qs = http_build_query($q);
        return $path . '?' . $qs;
    }

    function L($key) {
        global $LANG_STRINGS, $current_lang;
        if ($current_lang === 'fr') {
            $lang = 'fr';
        } elseif ($current_lang === 'he') {
            $lang = 'he';
        } else {
            $lang = 'en';
        }
        if (isset($LANG_STRINGS[$lang][$key])) {
            return $LANG_STRINGS[$lang][$key];
        }
        return isset($LANG_STRINGS['en'][$key]) ? $LANG_STRINGS['en'][$key] : $key;
    }
}

// Translation arrays
$LANG_STRINGS = [
    'en' => [
        'meta_title' => 'Alfred IDE — 13,000+ AI Tools | Voice AI | E-Commerce | From $0/mo',
        'meta_description' => 'The #1 AI hosting platform. 13,000+ tools, 17 AI engines, voice commands, e-commerce, SEO, DevOps, accessibility. Managed by Alfred AI. Start free.',
        'meta_keywords' => 'AI hosting platform, AI website builder, Alfred AI, voice AI hosting, AI e-commerce, Alfred IDE, AI IDE, 13,000+ tools',
        'og_locale' => 'en_US',
        'urgency_limited' => 'LIMITED TIME:',
        'urgency_offer' => 'Get 50% OFF your first year! Use code',
        'urgency_claim' => 'Claim Now →',
        'call_24_7' => 'Call Us 24/7 - Toll Free',
        'nav_hosting' => 'Hosting',
        'nav_wordpress_hosting' => 'WordPress Hosting',
        'nav_ai_hosting' => 'AI Hosting',
        'nav_dedicated_servers' => 'Dedicated Servers',
        'nav_ai_servers' => 'Build AI Server',
        'nav_gocodeme_editor' => 'Alfred IDE',
        'nav_use_online' => 'Use Online',
        'nav_download_app' => 'Download App',
        'nav_web_design' => 'Web Design',
        'nav_domains' => 'Domains',
        'nav_news' => 'News',
        'nav_cart' => 'Cart',
        'nav_support' => 'Support',
        'nav_login' => 'Login',
        'nav_get_started' => 'Get Started',
        'mobile_shared' => 'Shared Hosting',
        'mobile_vps' => 'VPS Hosting',
        'mobile_dedicated' => 'Dedicated Servers',
        'mobile_ai_hosting' => 'AI Hosting',
        'mobile_gocodeme_online' => 'Alfred IDE Online',
        'mobile_download_editor' => 'Download Editor',
        'mobile_web_design' => 'Web Design',
        'mobile_domains' => 'Domains',
        'mobile_news' => 'News',
        'mobile_contact' => 'Contact',
        'mobile_login' => 'Login',
        'mobile_get_started' => 'Get Started',
        'toll_free_24_7' => 'Toll-Free 24/7',
        'footer_tagline' => 'AI-powered web hosting that makes building websites faster and easier than ever before. Your success is our mission.',
        'footer_support_label' => 'Toll-Free 24/7 Support',
        'footer_hosting' => 'Hosting',
        'footer_domain_registration' => 'Domain Registration',
        'footer_ai_servers' => 'Build AI Server',
        'footer_products' => 'Products',
        'footer_ai_hosting_plans' => 'AI Hosting Plans',
        'footer_site_migration' => 'Site Migration',
        'footer_company' => 'Company',
        'footer_news_updates' => 'News & Updates',
        'footer_knowledge_base' => 'Knowledge Base',
        'footer_contact_us' => 'Contact Us',
        'footer_affiliate' => 'Affiliate Program',
        'footer_support' => 'Support',
        'footer_client_area' => 'Client Area',
        'footer_submit_ticket' => 'Submit Ticket',
        'footer_server_status' => 'Server Status',
        'footer_privacy' => 'Privacy Policy',
        'footer_terms' => 'Terms of Service',
        'footer_copyright' => '© 2026 GoSiteMe.com. All rights reserved.',
        'footer_rights' => 'All rights reserved.',
        'modal_welcome_back' => 'Welcome Back',
        'modal_sign_in_manage' => 'Sign in to manage your services',
        'modal_email' => 'Email Address',
        'modal_password' => 'Password',
        'modal_sign_in' => 'Sign In',
        'modal_no_account' => "Don't have an account? Sign up",
        'modal_forgot_password' => 'Forgot password?',
        'modal_create_account' => 'Create Account',
        'modal_get_started_today' => 'Get started with GoSiteMe today',
        'modal_first_name' => 'First Name',
        'modal_last_name' => 'Last Name',
        'modal_create_account_btn' => 'Create Account',
        'modal_have_account' => 'Already have an account? Sign in',
        'chat_title' => 'Chat with us',
        'hero_badge' => '13,000+ AI Tools — The #1 AI Development Platform',
        'hero_h1' => 'Build Stunning Websites',
        'hero_h1_highlight' => 'In Under 60 Seconds',
        'hero_subtitle' => "13,000+ AI Tools powered by 17 AI engines. Voice commands with command steering — queue commands while Alfred works, say stop to cancel, or keep talking. Phone support. WhatsApp & Discord. Code generation, image generation, e-commerce, SEO, DevOps, accessibility — all managed by Alfred AI. No coding required.",
        'hero_ai_hosting' => 'Get AI Hosting',
        'hero_download_gocodeme' => 'Download Alfred IDE',
        'hero_view_plans' => 'View All Plans',
        'hero_free_ssl' => 'Free SSL Certificate',
        'hero_free_migration' => 'Free Website Migration',
        'hero_money_back' => '30-Day Money Back',
        'hero_rating' => 'Rating',
        'hero_happy_customers' => 'Happy Customers',
        'hero_countries' => 'Countries',
        'hero_popular' => 'Popular:',
        'hero_popular_wp' => 'WordPress Hosting',
        'hero_popular_ai' => 'AI Hosting',
        'hero_popular_domains' => 'Domains',
        'floating_ai' => 'AI-Powered',
        'floating_build_60' => 'Build in 60 seconds',
        'floating_support' => '24/7 Support',
        'floating_help' => 'Always here to help',
        'floating_fast' => 'Blazing Fast',
        'floating_ssd' => 'SSD + LiteSpeed',
        'floating_uptime' => '99.9% Uptime',
        'floating_reliability' => 'Enterprise reliability',
        'floating_ssl' => 'Free SSL',
        'floating_secure' => 'Secure by default',
        'floating_sites_created' => '12 sites created',
        'floating_last_hour' => 'In the last hour',
        'floating_no_code' => 'No Code Needed',
        'floating_describe' => 'Describe it, we build it',
        'floating_guarantee' => '30-Day Guarantee',
        'floating_money_back' => 'Money back, no hassle',
        'floating_deploy' => '1-Click Deploy',
        'floating_live' => 'Live in seconds',
        'floating_free_domain' => 'Free Domain',
        'floating_annual' => 'With annual plans',
        'floating_backups' => 'Daily Backups',
        'floating_restore' => 'Restore anytime',
        'floating_staging' => 'Staging Sites',
        'floating_test_live' => 'Test before going live',
        'floating_migration' => 'Free Migration',
        'floating_we_move' => 'We move your site free',
        'floating_ai_design' => 'AI Design',
        'floating_every_device' => 'Beautiful on every device',
        'floating_wordpress' => 'WordPress Ready',
        'floating_one_click' => '1-click install',
        'floating_email' => 'Professional Email',
        'floating_included' => 'Included with hosting',
        'floating_ddos' => 'DDoS Protection',
        'floating_online' => 'Stay online, always',
        'floating_50k' => '50K+ sites powered',
        'floating_join' => 'Join happy customers',
        'stat_websites' => 'Websites Powered',
        'stat_uptime' => 'Uptime Guarantee',
        'stat_support' => 'Expert Support',
        'stat_ai_creation' => 'AI Site Creation',
        'trusted_by' => 'Trusted by businesses worldwide',
        'how_label' => 'Simple Process',
        'how_title' => 'Launch Your Website in 3 Steps',
        'how_subtitle' => 'No technical skills required. Our AI does the heavy lifting.',
        'step1_title' => 'Tell Us Your Vision',
        'step1_text' => 'Describe your business, choose your style, and let our AI understand exactly what you need.',
        'step2_title' => 'AI Creates Your Site',
        'step2_text' => 'Watch as our AI generates a stunning, fully-functional website in under 60 seconds.',
        'step3_title' => 'Go Live Instantly',
        'step3_text' => 'Connect your domain, make any tweaks, and launch. Your site is live and ready for visitors!',
        'how_cta' => 'Start Building Now',
        'how_note' => 'Takes less than 60 seconds',
        'how_try_free' => 'Or try the free online editor — no signup required',
        'ai_label' => 'AI Technology',
        'ai_title' => 'Meet Your New AI Web Designer',
        'ai_subtitle' => "Just describe what you want, and watch as our AI creates a professional website tailored to your vision. It's like magic, but better.",
        'ai_describe' => 'Describe your website',
        'ai_placeholder' => 'e.g., A modern portfolio website for a photographer with a dark theme, gallery section, about page, and contact form...',
        'ai_example_restaurant' => 'Restaurant website',
        'ai_example_store' => 'Online store',
        'ai_example_portfolio' => 'Portfolio',
        'ai_example_landing' => 'Landing page',
        'ai_preview_text' => 'Your AI-generated website will appear here',
        'ai_try_now' => 'Try It Now — From $15/mo',
        'features_label' => '🤖 13,000+ Tools',
        'features_title' => 'Everything You Need to Succeed Online',
        'features_subtitle' => '13,000+ AI Tools powered by 17 AI engines. Enterprise-grade infrastructure, voice AI, e-commerce, SEO, DevOps, and unmatched support — all at prices that make sense.',
        'feat_speed' => 'Blazing Fast Speed',
        'feat_speed_text' => 'LiteSpeed servers with NVMe SSD storage deliver page loads in milliseconds. Your visitors won\'t wait.',
        'feat_security' => 'Enterprise Security',
        'feat_security_text' => 'Free SSL certificates, DDoS protection, daily backups, and 24/7 monitoring keep your site safe.',
        'feat_ai' => '13,000+ AI Tools',
        'feat_ai_text' => 'The most powerful AI IDE with 13,000+ tools — e-commerce, SEO, DevOps, design, accessibility, customer intelligence, and more. Build anything with AI.',
        'feat_migration' => 'Free Migrations',
        'feat_migration_text' => 'Our experts will migrate your existing website for free. Zero downtime, zero hassle.',
        'feat_wp' => 'WordPress Optimized',
        'feat_wp_text' => 'Pre-configured for WordPress with automatic updates, staging environments, and one-click installs.',
        'feat_uptime' => '99.9% Uptime SLA',
        'feat_uptime_text' => 'Guaranteed uptime backed by our service level agreement. Your site stays online, period.',
        'feat_voice_ai' => 'Voice AI Assistant',
        'feat_voice_ai_text' => 'Talk to Alfred, your AI hosting assistant, with voice commands via browser or phone. Manage your entire website by conversation.',
        'feat_steering' => 'Command Steering',
        'feat_steering_text' => 'Queue commands while Alfred is executing — no waiting. Say "stop" or "cancel" to abort, or keep talking to add more. Alfred processes them in order, so you stay in flow.',
        'feat_ecommerce' => 'One-Click E-Commerce',
        'feat_ecommerce_text' => 'Set up an online store with AI-powered payments, invoicing, and shipping. Go from idea to selling in minutes.',
        'stat_ai_tools' => 'AI Tools Available',
        'stat_categories' => 'Tool Categories',
        'why_voice_steering' => 'Voice Steering',
        'pricing_label' => 'Simple Pricing',
        'pricing_title' => 'Choose Your Perfect Plan',
        'pricing_subtitle' => 'Transparent pricing with no hidden fees. Start small and scale as you grow.',
        'plan_wp1' => 'WordPress 1',
        'plan_wp1_tag' => 'Perfect for starters',
        'plan_wp3' => 'WordPress 3',
        'plan_wp3_tag' => 'Best for growing sites',
        'plan_ai' => 'Builder',
        'plan_ai_tag' => '300K AI tokens/month',
        'plan_wp5' => 'WordPress 5',
        'plan_wp5_tag' => 'For professionals',
        'billed_monthly' => 'Billed monthly',
        'build_60_note' => '300K tokens · Full IDE · Alfred AI',
        'most_popular' => 'Most Popular',
        'get_started' => 'Get Started',
        'try_ai_editor' => 'Try AI Editor',
        'need_more' => 'Need more power?',
        'check_dedicated' => 'Check out our Dedicated Servers',
        'domain_title' => 'Find Your Perfect Domain',
        'domain_subtitle' => 'Your journey starts with the right domain name. Search millions of available domains.',
        'domain_placeholder' => 'Enter your dream domain name...',
        'domain_search' => 'Search',
        'domain_checking' => 'Checking availability...',
        'domain_from' => 'from',
        'domain_yr' => '/yr',
        'services_label' => 'Services',
        'services_title' => 'Professional Web Solutions',
        'services_subtitle' => "From design to deployment, we've got you covered with comprehensive web services.",
        'service_design' => 'Token Top-Up Packs',
        'service_design_text' => 'Need more AI tokens? Buy a one-time pack — credited instantly, never expires. From 100K ($5) to 5M ($149). Add to any plan.',
        'service_design_from' => 'Starting from',
        'service_design_more' => 'Buy Tokens',
        'service_dedicated' => 'Build Your AI Server',
        'service_dedicated_text' => 'Configure a custom GPU-powered AI server with our interactive builder. Choose your CPU, GPU, RAM, and storage. Ships in 48 hours.',
        'service_dedicated_more' => 'Configure Now',
        'why_label' => 'Why Choose Us',
        'why_title' => "We're Not Like Other Hosts",
        'why_subtitle' => 'See how GoSiteMe stacks up against the competition',
        'why_feature' => 'Feature',
        'why_ai_builder' => 'AI Website Builder',
        'why_60_sec' => '60-Second Site Creation',
        'why_ssl' => 'Free SSL Certificate',
        'why_domain' => 'Free Domain (1st Year)',
        'why_support' => '24/7 Live Support',
        'why_litespeed' => 'LiteSpeed Servers',
        'why_migration' => 'Free Website Migration',
        'why_money_back' => '30-Day Money Back',
        'why_starting' => 'Starting Price',
        'why_extra' => 'Extra $',
        'why_limited' => 'Limited',
        'guarantee_title' => '30-Day Money-Back Guarantee',
        'guarantee_text' => 'Try us risk-free. Not satisfied? Get a full refund, no questions asked.',
        'testimonials_label' => 'Why GoSiteMe',
        'testimonials_title' => 'Built Different',
        'testimonials_subtitle' => 'Real features, real infrastructure, no gimmicks.',
        'testimonial1' => '"AI-powered website editor — describe what you want and get a full site in under 60 seconds. No templates, no drag-and-drop, just results."',
        'testimonial2' => '"Canadian-hosted infrastructure with fast load times, real human support, and pricing that makes sense. Built for speed and reliability."',
        'testimonial3' => '"Alfred AI with 842+ tools, voice calls, fleet management, and a full developer API. One platform for hosting, AI, and communications."',
        'verified_customer' => 'Platform Feature',
        'review_based' => '',
        'faq_label' => 'FAQ',
        'faq_title' => 'Frequently Asked Questions',
        'faq_subtitle' => "Got questions? We've got answers.",
        'faq1_q' => 'What is the AI Editor and how does it work?',
        'faq1_a' => 'Our AI Editor uses advanced artificial intelligence to create complete websites from text descriptions. Simply describe what you want, and the AI generates a fully-functional website with design, content, and functionality—all in under 60 seconds.',
        'faq2_q' => 'Do you offer a money-back guarantee?',
        'faq2_a' => "Yes! We offer a 30-day money-back guarantee on all hosting plans. If you're not completely satisfied, we'll refund your payment—no questions asked.",
        'faq3_q' => 'Can I migrate my existing website?',
        'faq3_a' => 'Absolutely! We offer free website migration for all new customers. Our expert team will handle the entire process with zero downtime. Just sign up and submit a migration request.',
        'faq4_q' => 'Is SSL included with hosting plans?',
        'faq4_a' => "Yes, all our hosting plans include free SSL certificates. Your website will be secured with HTTPS automatically, protecting your visitors' data and boosting your SEO.",
        'faq5_q' => 'What kind of support do you offer?',
        'faq5_a' => 'We provide 24/7 support via Alfred AI voice assistant, ticket system, and email. Our team of WordPress and hosting experts are always ready to help with any issues.',
        'faq6_q' => 'Can I upgrade my plan later?',
        'faq6_a' => "Yes, you can upgrade your plan at any time from your client area. The upgrade is instant and we'll prorate any remaining balance from your current plan.",
        'cta_title' => 'Ready to Launch Your Website?',
        'cta_subtitle' => 'Get your site online today with AI-powered tools and Canadian hosting.',
        'cta_btn' => 'Get Started with AI Editor',
        'cta_tagline' => 'AI development platform for creators, developers, and businesses. 13,000+ tools, 17 AI engines, voice AI, e-commerce, token packs, SSL, and 24/7 support.',
        'domain_available' => 'Available',
        'domain_taken' => 'Taken',
        'domain_check_at_checkout' => 'Add to cart to verify',
        'domain_add' => 'Add',
        'domain_search_error' => 'Error searching domains. Please try again.',
        'domain_connect_error' => 'Error connecting to server. Please try again.',
        'page_404_title' => 'Page Not Found | GoSiteMe',
        'page_404_heading' => 'Page Not Found',
        'page_404_text' => 'The page you\'re looking for doesn\'t exist or has been moved. Get back on track with the links below.',
        'page_404_home' => 'Go to Homepage',
        'page_404_contact' => 'Contact Support',
        'footer_explore' => 'Explore',
        'modal_close' => 'Close',
        'sign_out' => 'Sign Out',
        'alfred_badge' => 'World\'s First AI Hosting Assistant',
        'alfred_h2' => 'Meet Alfred. 13,000+ AI Tools.',
        'alfred_h2_line2' => 'Voice Commands. Phone Support. Messaging.',
        'alfred_sub' => 'The world\'s first AI that manages your entire website. Talk in your browser, call 1-833-GOSITEME by phone, or message from WhatsApp, Signal, or Discord. Generate images, set up e-commerce, run SEO audits, manage DevOps, fix accessibility. Install WordPress. Handle security. All by conversation.',
        'alfred_pill_voice' => 'Voice Commands',
        'alfred_pill_whatsapp' => 'WhatsApp',
        'alfred_pill_discord' => 'Discord',
        'alfred_pill_signal' => 'Signal',
        'alfred_pill_images' => 'AI Images',
        'alfred_pill_wordpress' => 'WordPress',
        'alfred_pill_security' => 'Security',
        'alfred_pill_billing' => 'Billing',
        'alfred_cta_discover' => 'Discover Alfred AI',
        'alfred_cta_start' => 'Start AI Hosting',
        'alfred_fine_print' => 'Included free with AI Hosting. No extra software. No extra cost. Use code',
        'alfred_fine_print2' => 'for 50% off your first year.',
        'enterprise_label' => 'Fortune 500 Capable',
        'enterprise_title' => 'What Fortune 500 Companies Pay Millions For',
        'enterprise_subtitle' => 'Alfred IDE doesn\'t just build blogs. It builds Fortune 500-quality websites. The same AI that powers your hosting can architect enterprise-grade dashboards, e-commerce platforms, SaaS applications, and multi-language marketing sites.',
        'enterprise_alfred_line' => 'You don\'t need a team of 50 developers anymore — Alfred IS the team.',
        'enterprise_cta' => 'Start Building Enterprise-Grade',
        'enterprise_bottom_title' => 'What Fortune 500 companies pay millions for, you build in hours.',
        'enterprise_bottom_sub' => 'Tell Alfred what you need. Watch it architect, design, code, and deploy — while you grab coffee.',
        'enterprise_saas_title' => 'SaaS Dashboards',
        'enterprise_saas_desc' => 'Real-time analytics, user management, subscription billing, role-based access. Full-stack SaaS — one conversation.',
        'enterprise_ecom_title' => 'E-Commerce Platforms',
        'enterprise_ecom_desc' => 'Product catalogs, payment gateways, inventory management, abandoned cart recovery. Shopify-level stores — no Shopify tax.',
        'enterprise_health_title' => 'Healthcare Portals',
        'enterprise_health_desc' => 'Patient scheduling, secure forms, HIPAA-conscious design, appointment booking, telehealth integration. Medical-grade UX.',
        'enterprise_fintech_title' => 'Fintech Dashboards',
        'enterprise_fintech_desc' => 'Financial data visualization, portfolio trackers, payment processing, compliance dashboards. Wall Street polish, startup speed.',
        'enterprise_realestate_title' => 'Real Estate Portals',
        'enterprise_realestate_desc' => 'MLS-style property listings, interactive maps, virtual tours, mortgage calculators, agent dashboards. Zillow-level power.',
        'enterprise_restaurant_title' => 'Restaurant Chains',
        'enterprise_restaurant_desc' => 'Online ordering, multi-location menus, reservation systems, delivery integration, loyalty programs. Enterprise food service — done.',
        'enterprise_law_title' => 'Law Firm Sites',
        'enterprise_law_desc' => 'Practice area pages, attorney profiles, case intake forms, client portals, document management. White-shoe firm credibility.',
        'enterprise_booking_title' => 'Booking Platforms',
        'enterprise_booking_desc' => 'Calendar scheduling, payment processing, automated reminders, multi-timezone support, staff management. Your own Calendly — owned by you.',

        // New navigation & page translations
        'nav_tools' => 'Tools',
        'nav_use_cases' => 'Use Cases',
        'nav_blog' => 'Blog',
        'nav_pricing' => 'Pricing',
        'nav_about' => 'About',
        'nav_docs' => 'Documentation',
        'nav_changelog' => "What's New",
        'nav_compare' => 'Compare',
        'nav_enterprise' => 'Enterprise',
        'tools_hero_title' => '13,000+ AI Tools — One Platform',
        'tools_hero_subtitle' => 'Search, filter, and explore every tool Alfred has to offer',
        'tools_search_placeholder' => 'Search tools...',
        'use_cases_title' => 'Alfred AI for Everyone',
        'use_cases_subtitle' => 'Discover how Alfred helps professionals across every industry',
        'blog_title' => 'Alfred AI Blog',
        'blog_subtitle' => 'Tutorials, insights, and announcements',
        'pricing_title' => 'Simple, Transparent Pricing',
        'pricing_subtitle' => 'Start free, upgrade when you need more power',
        'about_title' => 'About GoSiteMe',
        'about_subtitle' => 'Building the future of AI from Montreal',
        'docs_title' => 'Documentation',
        'docs_subtitle' => 'Everything you need to integrate Alfred',
        'changelog_title' => "What's New in Alfred",
        'compare_title' => 'Why Alfred Wins',
        'enterprise_title' => 'Alfred for Enterprise',
        'cta_try_free' => 'Try Alfred Free',
        'cta_start_trial' => 'Start 14-Day Free Trial',
        'cta_view_pricing' => 'View Pricing',
        'footer_tools' => 'Tool Directory',
        'footer_blog' => 'Blog',
        'footer_docs' => 'Documentation',
        'footer_about' => 'About Us',
        'footer_changelog' => 'Changelog',
        'footer_compare' => 'Compare',
        'footer_enterprise' => 'Enterprise',
        'footer_marketplace' => 'Marketplace',
        'nav_tools' => 'Tools',
        'nav_alfred' => 'Alfred AI',

        // ========== Sprint 1 & 2 Translation Keys ==========

        // Developer Portal
        'dev_portal_title' => 'Developer Portal',
        'dev_portal_subtitle' => 'Build with Alfred AI',
        'api_playground' => 'API Playground',
        'api_keys' => 'API Keys',
        'generate_key' => 'Generate API Key',
        'key_name' => 'Key Name',
        'key_permissions' => 'Permissions',
        'webhooks' => 'Webhooks',
        'oauth_apps' => 'OAuth Apps',
        'rate_limits' => 'Rate Limits',
        'sdks' => 'SDKs',

        // Extensions
        'extensions_title' => 'Alfred AI Extensions',
        'chrome_extension' => 'Chrome Extension',
        'cli_tool' => 'Command Line Tool',
        'install_extension' => 'Install Extension',
        'extension_features' => 'Extension Features',

        // IVR Builder
        'ivr_builder_title' => 'IVR Flow Builder',
        'ivr_subtitle' => 'Design voice menus visually',
        'add_node' => 'Add Node',
        'menu_node' => 'Menu',
        'greeting_node' => 'Greeting',
        'transfer_node' => 'Transfer',
        'voicemail_node' => 'Voicemail',
        'condition_node' => 'Condition',
        'save_flow' => 'Save Flow',
        'deploy_flow' => 'Deploy Flow',

        // Voice Cloning
        'voice_cloning_title' => 'Voice Cloning Studio',
        'clone_voice' => 'Clone Your Voice',
        'upload_sample' => 'Upload Voice Sample',
        'voice_profile' => 'Voice Profile',
        'voice_quality' => 'Voice Quality',
        'train_model' => 'Train Model',

        // Call Campaigns
        'call_campaigns_title' => 'Call Campaigns',
        'create_campaign' => 'Create Campaign',
        'campaign_name' => 'Campaign Name',
        'contact_list' => 'Contact List',
        'campaign_script' => 'Call Script',
        'schedule_campaign' => 'Schedule',
        'campaign_stats' => 'Campaign Statistics',
        'calls_completed' => 'Calls Completed',
        'calls_pending' => 'Calls Pending',
        'success_rate' => 'Success Rate',

        // Enterprise Admin
        'enterprise_admin_title' => 'Enterprise Admin',
        'org_settings' => 'Organization Settings',
        'team_members' => 'Team Members',
        'invite_member' => 'Invite Member',
        'member_role' => 'Role',
        'role_admin' => 'Admin',
        'role_manager' => 'Manager',
        'role_member' => 'Member',
        'role_viewer' => 'Viewer',
        'audit_log' => 'Audit Log',
        'sso_settings' => 'SSO Settings',
        'security_settings' => 'Security Settings',
        'usage_quotas' => 'Usage Quotas',

        // Affiliate
        'affiliate_title' => 'Affiliate Program',
        'affiliate_subtitle' => 'Earn 30% recurring commission',
        'referral_link' => 'Your Referral Link',
        'total_referrals' => 'Total Referrals',
        'total_earnings' => 'Total Earnings',
        'pending_payout' => 'Pending Payout',
        'request_payout' => 'Request Payout',
        'affiliate_terms' => 'Affiliate Terms',

        // Status Page
        'status_title' => 'System Status',
        'all_systems_operational' => 'All Systems Operational',
        'degraded_performance' => 'Degraded Performance',
        'partial_outage' => 'Partial Outage',
        'major_outage' => 'Major Outage',
        'uptime' => 'Uptime',
        'response_time' => 'Response Time',
        'incident_history' => 'Incident History',

        // Analytics
        'analytics_title' => 'Analytics',
        'analytics_subtitle' => 'Understand your usage patterns',
        'time_range' => 'Time Range',
        'today' => 'Today',
        'last_7_days' => 'Last 7 Days',
        'last_30_days' => 'Last 30 Days',
        'last_90_days' => 'Last 90 Days',
        'api_calls' => 'API Calls',
        'voice_minutes' => 'Voice Minutes',
        'active_agents' => 'Active Agents',
        'tools_executed' => 'Tools Executed',
        'fleet_uptime' => 'Fleet Uptime',
        'storage_used' => 'Storage Used',
        'top_tools' => 'Top Tools',
        'agent_performance' => 'Agent Performance',
        'cost_analysis' => 'Cost Analysis',
        'projected_cost' => 'Projected Monthly Cost',
        'activity_log' => 'Activity Log',

        // Webhooks
        'webhooks_title' => 'Webhook Events',
        'webhooks_subtitle' => 'Get real-time notifications',
        'create_webhook' => 'Create Webhook',
        'webhook_url' => 'Webhook URL',
        'webhook_events' => 'Events',
        'webhook_secret' => 'Signing Secret',
        'webhook_active' => 'Active',
        'webhook_paused' => 'Paused',
        'webhook_disabled' => 'Disabled',
        'delivery_log' => 'Delivery Log',
        'test_webhook' => 'Send Test',
        'event_reference' => 'Event Reference',

        // Marketplace Creator
        'creator_dashboard' => 'Creator Dashboard',
        'my_products' => 'My Products',
        'add_product' => 'Add New Product',
        'product_earnings' => 'Earnings',
        'reviews_ratings' => 'Reviews & Ratings',
        'creator_settings' => 'Creator Settings',
        'creator_analytics' => 'Creator Analytics',
        'total_downloads' => 'Total Downloads',
        'total_revenue' => 'Total Revenue',
        'average_rating' => 'Average Rating',
        'publish_product' => 'Submit for Review',
        'save_draft' => 'Save as Draft',
        'product_type' => 'Product Type',
        'product_category' => 'Category',
        'product_tags' => 'Tags',
        'product_price' => 'Price',
        'commission_rate' => '70% Commission',
        'request_payout_btn' => 'Request Payout',
        'minimum_payout' => 'Minimum payout: $25',

        // SDKs Page
        'sdks_title' => 'Alfred AI SDKs',
        'sdks_subtitle' => 'Integrate in minutes',
        'quick_start' => 'Quick Start',
        'installation' => 'Installation',
        'code_examples' => 'Code Examples',
        'type_safe' => 'Type-Safe',
        'auto_retry' => 'Auto-Retry',
        'streaming_support' => 'Streaming Support',

        // Notifications
        'notifications' => 'Notifications',
        'mark_all_read' => 'Mark All Read',
        'no_notifications' => 'No notifications',
        'view_all' => 'View All',
        'notification_preferences' => 'Notification Preferences',

        // Pricing (6 tiers)
        'plan_free' => 'Free',
        'plan_starter' => 'Starter',
        'plan_professional' => 'Professional',
        'plan_enterprise' => 'Enterprise',
        'plan_enterprise_plus' => 'Enterprise Plus',
        'plan_custom' => 'Custom',
        'monthly_billing' => 'Monthly',
        'annual_billing' => 'Annual',
        'save_17_percent' => 'Save 17%',
        'per_month' => '/month',
        'per_year' => '/year',
        'billed_annually' => 'Billed annually',
        'contact_sales' => 'Contact Sales',
        'compare_plans' => 'Compare Plans',
        'feature_comparison' => 'Feature Comparison',
        'overage_charges' => 'Overage Charges',

        // Common new terms
        'oauth' => 'OAuth',
        'authorization' => 'Authorization',
        'scopes' => 'Scopes',
        'access_token' => 'Access Token',
        'refresh_token' => 'Refresh Token',
        'client_id' => 'Client ID',
        'client_secret' => 'Client Secret',
        'redirect_uri' => 'Redirect URI',
        'revoke' => 'Revoke',
        'expires' => 'Expires',
        'metered_billing' => 'Metered Billing',
        'current_usage' => 'Current Usage',
        'usage_limit' => 'Usage Limit',
        'unlimited' => 'Unlimited',
        'api_reference' => 'API Reference',
        'getting_started' => 'Getting Started',
        'documentation' => 'Documentation',
        'copy_to_clipboard' => 'Copy to clipboard',
        'copied' => 'Copied!',
        'loading' => 'Loading...',
        'no_data' => 'No data available',
        'error_occurred' => 'An error occurred',
        'try_again' => 'Try Again',
        'confirm_action' => 'Are you sure?',
        'yes_delete' => 'Yes, delete',
        'cancel' => 'Cancel',
        'save_changes' => 'Save Changes',
        'export_data' => 'Export Data',
        'import_data' => 'Import Data',
        'filter_by' => 'Filter By',
        'sort_by' => 'Sort By',
        'ascending' => 'Ascending',
        'descending' => 'Descending',
        'showing_results' => 'Showing results',
        'no_results' => 'No results found',
        'items_per_page' => 'Items per page',

        // Accessibility (shell chrome — used sitewide with site-header / site-footer)
        'a11y_skip_to_main' => 'Skip to main content',
        'a11y_main_nav' => 'Main navigation',
        'a11y_site_footer' => 'Site footer',
        'a11y_open_editor' => 'Open Editor Directly',
        'a11y_back_to_top' => 'Back to top',
        'a11y_close_menu' => 'Close menu',
        'a11y_account_nav' => 'Account',
        'a11y_dashboard_btn' => 'Dashboard',
        'a11y_my_account_btn' => 'My Account',
        'a11y_language_label' => 'Language',
    ],
    'fr' => [
        'meta_title' => 'Alfred IDE — 13,000+ outils IA | IA vocale | E-Commerce | Dès 0 $/mois',
        'meta_description' => 'La plateforme d\'hébergement IA #1. 13,000+ outils, 17 moteurs IA, commandes vocales, e-commerce, SEO, DevOps, accessibilité. Géré par Alfred IA. Commencez gratuitement.',
        'meta_keywords' => 'plateforme hébergement IA, créateur de site IA, Alfred IA, hébergement IA vocal, e-commerce IA, Alfred IDE, IDE IA, 250 outils',
        'og_locale' => 'fr_FR',
        'urgency_limited' => 'OFFRE LIMITÉE :',
        'urgency_offer' => 'Obtenez 50 % de réduction la première année ! Code',
        'urgency_claim' => 'En profiter →',
        'call_24_7' => 'Appelez-nous 24 h/24, 7 j/7 - Sans frais',
        'nav_hosting' => 'Hébergement',
        'nav_wordpress_hosting' => 'Hébergement WordPress',
        'nav_ai_hosting' => 'Hébergement IA',
        'nav_dedicated_servers' => 'Serveurs dédiés',
        'nav_ai_servers' => 'Configurer serveur IA',
        'nav_gocodeme_editor' => 'Alfred IDE',
        'nav_use_online' => 'Utiliser en ligne',
        'nav_download_app' => 'Télécharger l\'app',
        'nav_web_design' => 'Conception Web',
        'nav_domains' => 'Domaines',
        'nav_news' => 'Actualités',
        'nav_support' => 'Support',
        'nav_login' => 'Connexion',
        'nav_get_started' => 'Commencer',
        'mobile_shared' => 'Hébergement partagé',
        'mobile_vps' => 'Hébergement VPS',
        'mobile_dedicated' => 'Serveurs dédiés',
        'mobile_ai_hosting' => 'Hébergement IA',
        'mobile_gocodeme_online' => 'Alfred IDE en ligne',
        'mobile_download_editor' => 'Télécharger l\'éditeur',
        'mobile_web_design' => 'Conception Web',
        'mobile_domains' => 'Domaines',
        'mobile_news' => 'Actualités',
        'mobile_contact' => 'Contact',
        'mobile_login' => 'Connexion',
        'mobile_get_started' => 'Commencer',
        'toll_free_24_7' => 'Sans frais 24/7',
        'footer_tagline' => 'Hébergement web propulsé par l\'IA pour créer des sites plus rapidement et plus facilement. Votre succès est notre mission.',
        'footer_support_label' => 'Support 24/7 sans frais',
        'footer_hosting' => 'Hébergement',
        'footer_domain_registration' => 'Enregistrement de domaine',
        'footer_ai_servers' => 'Configurer serveur IA',
        'footer_products' => 'Produits',
        'footer_ai_hosting_plans' => 'Forfaits hébergement IA',
        'footer_site_migration' => 'Migration de site',
        'footer_company' => 'Entreprise',
        'footer_news_updates' => 'Actualités et mises à jour',
        'footer_knowledge_base' => 'Base de connaissances',
        'footer_contact_us' => 'Nous joindre',
        'footer_affiliate' => 'Programme d\'affiliation',
        'footer_support' => 'Support',
        'footer_client_area' => 'Espace client',
        'footer_submit_ticket' => 'Ouvrir un billet',
        'footer_server_status' => 'État des serveurs',
        'footer_privacy' => 'Politique de confidentialité',
        'footer_terms' => 'Conditions d\'utilisation',
        'footer_copyright' => '© 2026 GoSiteMe.com. Tous droits réservés.',
        'footer_rights' => 'Tous droits réservés.',
        'modal_welcome_back' => 'Bon retour',
        'modal_sign_in_manage' => 'Connectez-vous pour gérer vos services',
        'modal_email' => 'Adresse courriel',
        'modal_password' => 'Mot de passe',
        'modal_sign_in' => 'Connexion',
        'modal_no_account' => 'Pas de compte ? Inscrivez-vous',
        'modal_forgot_password' => 'Mot de passe oublié ?',
        'modal_create_account' => 'Créer un compte',
        'modal_get_started_today' => 'Commencez avec GoSiteMe aujourd\'hui',
        'modal_first_name' => 'Prénom',
        'modal_last_name' => 'Nom de famille',
        'modal_create_account_btn' => 'Créer un compte',
        'modal_have_account' => 'Déjà un compte ? Connexion',
        'chat_title' => 'Discutez avec nous',
        'hero_badge' => '13,000+ outils IA — La plateforme de développement IA #1',
        'hero_h1' => 'Créez des sites époustouflants',
        'hero_h1_highlight' => 'En moins de 60 secondes',
        'hero_subtitle' => "13,000+ outils IA propulsés par 17 moteurs IA. Commandes vocales avec pilotage de commandes — empilez des commandes pendant qu'Alfred travaille, dites stop pour annuler, ou continuez à parler. Support téléphonique. WhatsApp et Discord. Génération de code, d'images, e-commerce, SEO, DevOps, accessibilité — le tout géré par Alfred IA. Aucun code requis.",
        'hero_ai_hosting' => 'Hébergement IA',
        'hero_download_gocodeme' => 'Télécharger Alfred IDE',
        'hero_view_plans' => 'Voir les forfaits',
        'hero_free_ssl' => 'Certificat SSL gratuit',
        'hero_free_migration' => 'Migration gratuite',
        'hero_money_back' => 'Garantie 30 jours',
        'hero_rating' => 'Note',
        'hero_happy_customers' => 'Clients satisfaits',
        'hero_countries' => 'Pays',
        'hero_popular' => 'Populaires :',
        'hero_popular_wp' => 'Hébergement WordPress',
        'hero_popular_ai' => 'Hébergement IA',
        'hero_popular_domains' => 'Domaines',
        'floating_ai' => 'Propulsé par l\'IA',
        'floating_build_60' => 'Création en 60 s',
        'floating_support' => 'Support 24/7',
        'floating_help' => 'Toujours là pour vous',
        'floating_fast' => 'Ultra rapide',
        'floating_ssd' => 'SSD + LiteSpeed',
        'floating_uptime' => '99,9 % de disponibilité',
        'floating_reliability' => 'Fiabilité professionnelle',
        'floating_ssl' => 'SSL gratuit',
        'floating_secure' => 'Sécurisé par défaut',
        'floating_sites_created' => '12 sites créés',
        'floating_last_hour' => 'Dans la dernière heure',
        'floating_no_code' => 'Sans code',
        'floating_describe' => 'Décrivez, on construit',
        'floating_guarantee' => 'Garantie 30 jours',
        'floating_money_back' => 'Remboursé, sans tracas',
        'floating_deploy' => 'Déploiement en 1 clic',
        'floating_live' => 'En ligne en secondes',
        'floating_free_domain' => 'Domaine gratuit',
        'floating_annual' => 'Avec forfaits annuels',
        'floating_backups' => 'Sauvegardes quotidiennes',
        'floating_restore' => 'Restaurez à tout moment',
        'floating_staging' => 'Sites de test',
        'floating_test_live' => 'Testez avant la mise en ligne',
        'floating_migration' => 'Migration gratuite',
        'floating_we_move' => 'On migre votre site gratuitement',
        'floating_ai_design' => 'Design IA',
        'floating_every_device' => 'Parfait sur tous les appareils',
        'floating_wordpress' => 'Prêt pour WordPress',
        'floating_one_click' => 'Installation en 1 clic',
        'floating_email' => 'Courriel professionnel',
        'floating_included' => 'Inclus avec l\'hébergement',
        'floating_ddos' => 'Protection DDoS',
        'floating_online' => 'Restez en ligne, toujours',
        'floating_50k' => 'Plus de 50 K sites',
        'floating_join' => 'Rejoignez des clients satisfaits',
        'stat_websites' => 'Sites hébergés',
        'stat_uptime' => 'Disponibilité garantie',
        'stat_support' => 'Support expert',
        'stat_ai_creation' => 'Création de site IA',
        'trusted_by' => 'Approuvé par des entreprises du monde entier',
        'how_label' => 'Processus simple',
        'how_title' => 'Lancez votre site en 3 étapes',
        'how_subtitle' => 'Aucune compétence technique requise. Notre IA s\'occupe de tout.',
        'step1_title' => 'Décrivez votre vision',
        'step1_text' => 'Décrivez votre entreprise, choisissez votre style, et notre IA comprendra exactement ce dont vous avez besoin.',
        'step2_title' => 'L\'IA crée votre site',
        'step2_text' => 'Regardez notre IA générer un site magnifique et fonctionnel en moins de 60 secondes.',
        'step3_title' => 'Mettez en ligne instantanément',
        'step3_text' => 'Connectez votre domaine, ajustez si besoin, et lancez. Votre site est en ligne et prêt pour vos visiteurs !',
        'how_cta' => 'Commencer maintenant',
        'how_note' => 'Moins de 60 secondes',
        'how_try_free' => 'Ou essayez l\'éditeur en ligne gratuit — sans inscription',
        'ai_label' => 'Technologie IA',
        'ai_title' => 'Votre nouveau concepteur web IA',
        'ai_subtitle' => 'Décrivez ce que vous voulez et regardez l\'IA créer un site professionnel sur mesure. Comme par magie, en mieux.',
        'ai_describe' => 'Décrivez votre site web',
        'ai_placeholder' => 'Ex. : Un portfolio moderne pour un photographe, thème sombre, galerie, page à propos et formulaire de contact...',
        'ai_example_restaurant' => 'Site de restaurant',
        'ai_example_store' => 'Boutique en ligne',
        'ai_example_portfolio' => 'Portfolio',
        'ai_example_landing' => 'Page d\'accueil',
        'ai_preview_text' => 'Votre site généré par l\'IA apparaîtra ici',
        'ai_try_now' => 'Essayer — Dès 15 $/mois',
        'features_label' => '🤖 13,000+ outils',
        'features_title' => 'Tout pour réussir en ligne',
        'features_subtitle' => '13,000+ outils IA propulsés par 17 moteurs IA. Infrastructure de niveau entreprise, IA vocale, e-commerce, SEO, DevOps et un support inégalé — à des prix raisonnables.',
        'feat_speed' => 'Vitesse fulgurante',
        'feat_speed_text' => 'Serveurs LiteSpeed et stockage NVMe SSD pour des chargements en millisecondes.',
        'feat_security' => 'Sécurité professionnelle',
        'feat_security_text' => 'SSL gratuit, protection DDoS, sauvegardes quotidiennes et surveillance 24/7.',
        'feat_ai' => '13,000+ outils IA',
        'feat_ai_text' => 'L\'IDE IA le plus puissant avec 250 outils — e-commerce, SEO, DevOps, design, accessibilité, intelligence client et plus. Construisez tout avec l\'IA.',
        'feat_migration' => 'Migrations gratuites',
        'feat_migration_text' => 'Nos experts migrent votre site gratuitement. Zéro interruption, zéro tracas.',
        'feat_wp' => 'Optimisé WordPress',
        'feat_wp_text' => 'Préconfiguré pour WordPress : mises à jour automatiques, environnements de test et installation en 1 clic.',
        'feat_uptime' => 'Disponibilité 99,9 %',
        'feat_uptime_text' => 'Disponibilité garantie par notre accord de niveau de service.',
        'feat_voice_ai' => 'Assistant IA vocal',
        'feat_voice_ai_text' => 'Parlez à Alfred, votre assistant IA d\'hébergement, avec des commandes vocales via navigateur ou téléphone. Gérez tout votre site par conversation.',
        'feat_steering' => 'Pilotage de commandes',
        'feat_steering_text' => 'Empilez des commandes pendant qu\'Alfred exécute — sans attendre. Dites « stop » ou « annuler » pour interrompre, ou continuez à parler. Alfred les traite dans l\'ordre.',
        'feat_ecommerce' => 'E-Commerce en 1 clic',
        'feat_ecommerce_text' => 'Créez une boutique en ligne avec paiements, facturation et expédition propulsés par l\'IA. Du concept à la vente en quelques minutes.',
        'stat_ai_tools' => 'Outils IA disponibles',
        'stat_categories' => 'Catégories d\'outils',
        'why_voice_steering' => 'Pilotage vocal',
        'pricing_label' => 'Tarification simple',
        'pricing_title' => 'Choisissez le forfait idéal',
        'pricing_subtitle' => 'Tarification transparente, sans frais cachés. Démarrez petit et évoluez.',
        'plan_wp1' => 'WordPress 1',
        'plan_wp1_tag' => 'Idéal pour débuter',
        'plan_wp3' => 'WordPress 3',
        'plan_wp3_tag' => 'Pour les sites en croissance',
        'plan_ai' => 'Builder',
        'plan_ai_tag' => '300K jetons IA/mois',
        'plan_wp5' => 'WordPress 5',
        'plan_wp5_tag' => 'Pour les professionnels',
        'billed_monthly' => 'Facturé mensuellement',
        'build_60_note' => '300K jetons · IDE complet · Alfred IA',
        'most_popular' => 'Le plus populaire',
        'get_started' => 'Commencer',
        'try_ai_editor' => 'Essayer l\'éditeur IA',
        'need_more' => 'Besoin de plus de puissance ?',
        'check_dedicated' => 'Découvrez nos serveurs dédiés',
        'domain_title' => 'Trouvez le domaine idéal',
        'domain_subtitle' => 'Votre aventure commence par le bon nom de domaine. Des millions de domaines disponibles.',
        'domain_placeholder' => 'Entrez le nom de domaine de vos rêves...',
        'domain_search' => 'Rechercher',
        'domain_checking' => 'Vérification en cours...',
        'domain_from' => 'à partir de',
        'domain_yr' => '/an',
        'services_label' => 'Services',
        'services_title' => 'Solutions web professionnelles',
        'services_subtitle' => 'De la conception au déploiement, nous vous accompagnons avec des services web complets.',
        'service_design' => 'Packs de jetons',
        'service_design_text' => 'Besoin de plus de jetons IA ? Achetez un pack unique — crédité instantanément, n\'expire jamais. De 100K (5 $) à 5M (149 $).',
        'service_design_from' => 'À partir de',
        'service_design_more' => 'Acheter',
        'service_dedicated' => 'Construisez votre serveur IA',
        'service_dedicated_text' => 'Configurez un serveur IA sur mesure avec GPU. Choisissez CPU, GPU, RAM et stockage. Livraison en 48 heures.',
        'service_dedicated_more' => 'Configurer',
        'why_label' => 'Pourquoi nous choisir',
        'why_title' => 'Nous ne sommes pas comme les autres',
        'why_subtitle' => 'Comparez GoSiteMe à la concurrence',
        'why_feature' => 'Fonctionnalité',
        'why_ai_builder' => 'Créateur de sites IA',
        'why_60_sec' => 'Création en 60 secondes',
        'why_ssl' => 'Certificat SSL gratuit',
        'why_domain' => 'Domaine gratuit (1re année)',
        'why_support' => 'Support 24/7',
        'why_litespeed' => 'Serveurs LiteSpeed',
        'why_migration' => 'Migration gratuite',
        'why_money_back' => 'Garantie 30 jours',
        'why_starting' => 'Prix à partir de',
        'why_extra' => 'En supplément',
        'why_limited' => 'Limité',
        'guarantee_title' => 'Garantie de remboursement 30 jours',
        'guarantee_text' => 'Essayez sans risque. Pas satisfait ? Remboursement intégral, sans questions.',
        'testimonials_label' => 'Pourquoi GoSiteMe',
        'testimonials_title' => 'Construit différemment',
        'testimonials_subtitle' => 'Fonctionnalités réelles, infrastructure réelle, sans artifice.',
        'testimonial1' => '« Éditeur de sites par IA — décrivez ce que vous voulez et obtenez un site complet en moins de 60 secondes. Sans modèle, sans glisser-déposer, juste des résultats. »',
        'testimonial2' => '« Infrastructure hébergée au Canada avec des temps de chargement rapides, du support humain réel, et des prix qui ont du sens. Conçu pour la vitesse et la fiabilité. »',
        'testimonial3' => '« Alfred IA avec 1 220+ outils, appels vocaux, gestion de flotte et une API développeur complète. Une seule plateforme pour l’hébergement, l’IA et les communications. »',
        'verified_customer' => 'Fonctionnalité',
        'review_based' => '',
        'faq_label' => 'FAQ',
        'faq_title' => 'Questions fréquentes',
        'faq_subtitle' => 'Des questions ? Nous avons les réponses.',
        'faq1_q' => 'Qu’est-ce que l’éditeur IA et comment ça marche ?',
        'faq1_a' => 'Notre éditeur IA utilise l’intelligence artificielle pour créer des sites complets à partir de descriptions textuelles. Décrivez ce que vous voulez et l’IA génère un site fonctionnel en moins de 60 secondes.',
        'faq2_q' => 'Offrez-vous une garantie de remboursement ?',
        'faq2_a' => 'Oui ! Garantie de remboursement de 30 jours sur tous les forfaits d’hébergement. Pas satisfait ? Remboursement intégral, sans questions.',
        'faq3_q' => 'Puis-je migrer mon site existant ?',
        'faq3_a' => 'Absolument ! Nous offrons la migration gratuite pour tous les nouveaux clients. Notre équipe s’en occupe avec zéro interruption. Inscrivez-vous et soumettez une demande de migration.',
        'faq4_q' => 'Le SSL est-il inclus avec l’hébergement ?',
        'faq4_a' => 'Oui, tous nos forfaits incluent un certificat SSL gratuit. Votre site sera sécurisé en HTTPS automatiquement.',
        'faq5_q' => 'Quel type de support offrez-vous ?',
        'faq5_a' => 'Support 24/7 par Alfred AI assistant vocal, billet et courriel. Notre équipe d\'experts WordPress et hébergement est toujours prête à vous aider.',
        'faq6_q' => 'Puis-je améliorer mon forfait plus tard ?',
        'faq6_a' => 'Oui, vous pouvez améliorer votre forfait à tout moment depuis l’espace client. La mise à niveau est instantanée et nous proportionnons le solde restant.',
        'cta_title' => 'Prêt à lancer votre site ?',
        'cta_subtitle' => 'Mettez votre site en ligne aujourd’hui avec des outils IA et un hébergement canadien.',
        'cta_btn' => 'Commencer avec l’éditeur IA',
        'cta_tagline' => 'Plateforme de développement IA pour créateurs, développeurs et entreprises. 13,000+ outils, 17 moteurs IA, IA vocale, e-commerce, packs de jetons, SSL et support 24/7.',
        'domain_available' => 'Disponible',
        'domain_taken' => 'Pris',
        'domain_check_at_checkout' => 'Ajouter au panier pour vérifier',
        'domain_add' => 'Ajouter',
        'domain_search_error' => 'Erreur lors de la recherche. Veuillez réessayer.',
        'domain_connect_error' => 'Erreur de connexion au serveur. Veuillez réessayer.',
        'page_404_title' => 'Page introuvable | GoSiteMe',
        'page_404_heading' => 'Page introuvable',
        'page_404_text' => 'La page demandée n\'existe pas ou a été déplacée. Utilisez les liens ci-dessous pour continuer.',
        'page_404_home' => 'Retour à l\'accueil',
        'page_404_contact' => 'Contacter le support',
        'footer_explore' => 'Explorer',
        'modal_close' => 'Fermer',
        'sign_out' => 'Déconnexion',
        'alfred_badge' => 'Le tout premier assistant d\'hébergement IA au monde',
        'alfred_h2' => 'Découvrez Alfred. 13,000+ outils IA.',
        'alfred_h2_line2' => 'Commandes vocales. Support téléphonique. Messagerie.',
        'alfred_sub' => 'La première IA au monde qui gère tout votre site web. Parlez dans votre navigateur, appelez le 1-833-GOSITEME par téléphone, ou envoyez un message via WhatsApp, Signal ou Discord. Générez des images, créez une boutique e-commerce, lancez des audits SEO, gérez le DevOps, corrigez l\'accessibilité. Installez WordPress. Sécurisez votre site. Le tout par conversation.',
        'alfred_pill_voice' => 'Commandes vocales',
        'alfred_pill_whatsapp' => 'WhatsApp',
        'alfred_pill_discord' => 'Discord',
        'alfred_pill_signal' => 'Signal',
        'alfred_pill_images' => 'Images IA',
        'alfred_pill_wordpress' => 'WordPress',
        'alfred_pill_security' => 'Sécurité',
        'alfred_pill_billing' => 'Facturation',
        'alfred_cta_discover' => 'Découvrir Alfred IA',
        'alfred_cta_start' => 'Hébergement IA',
        'alfred_fine_print' => 'Inclus avec l\'hébergement IA. Aucun logiciel supplémentaire. Aucun coût additionnel. Utilisez le code',
        'alfred_fine_print2' => 'pour 50 % de réduction la première année.',
        'enterprise_label' => 'Niveau Fortune 500',
        'enterprise_title' => 'Ce que les entreprises Fortune 500 paient des millions',
        'enterprise_subtitle' => 'Alfred IDE ne fait pas que des blogues. Il construit des sites web de qualité Fortune 500. La même IA qui alimente votre hébergement peut concevoir des tableaux de bord d\'entreprise, des plateformes e-commerce, des applications SaaS et des sites marketing multilingues.',
        'enterprise_alfred_line' => 'Vous n\'avez plus besoin d\'une équipe de 50 développeurs — Alfred EST l\'équipe.',
        'enterprise_cta' => 'Commencer à construire — niveau entreprise',
        'enterprise_bottom_title' => 'Ce que les Fortune 500 paient des millions, vous le construisez en quelques heures.',
        'enterprise_bottom_sub' => 'Dites à Alfred ce dont vous avez besoin. Regardez-le concevoir, designer, coder et déployer — pendant que vous prenez un café.',
        'enterprise_saas_title' => 'Tableaux de bord SaaS',
        'enterprise_saas_desc' => 'Analytiques en temps réel, gestion des utilisateurs, facturation par abonnement, accès basé sur les rôles. SaaS complet — une seule conversation.',
        'enterprise_ecom_title' => 'Plateformes E-Commerce',
        'enterprise_ecom_desc' => 'Catalogues de produits, passerelles de paiement, gestion des stocks, récupération de paniers abandonnés. Boutiques niveau Shopify — sans la taxe Shopify.',
        'enterprise_health_title' => 'Portails Santé',
        'enterprise_health_desc' => 'Prise de rendez-vous, formulaires sécurisés, design conforme HIPAA, réservation, intégration télésanté. UX de qualité médicale.',
        'enterprise_fintech_title' => 'Tableaux de bord Fintech',
        'enterprise_fintech_desc' => 'Visualisation de données financières, suivi de portefeuille, traitement des paiements, tableaux de conformité. L\'élégance de Wall Street, la vitesse d\'une startup.',
        'enterprise_realestate_title' => 'Portails Immobiliers',
        'enterprise_realestate_desc' => 'Annonces immobilières style MLS, cartes interactives, visites virtuelles, calculateurs hypothécaires, tableaux de bord pour agents. La puissance de Zillow.',
        'enterprise_restaurant_title' => 'Chaînes de Restaurants',
        'enterprise_restaurant_desc' => 'Commande en ligne, menus multi-sites, systèmes de réservation, intégration livraison, programmes de fidélité. Service alimentaire d\'entreprise — fait.',
        'enterprise_law_title' => 'Sites de Cabinets Juridiques',
        'enterprise_law_desc' => 'Pages de pratique, profils d\'avocats, formulaires d\'admission, portails clients, gestion documentaire. Crédibilité de grand cabinet.',
        'enterprise_booking_title' => 'Plateformes de Réservation',
        'enterprise_booking_desc' => 'Planification par calendrier, traitement des paiements, rappels automatiques, support multi-fuseaux, gestion du personnel. Votre propre Calendly — qui vous appartient.',

        // New navigation & page translations (French)
        'nav_tools' => 'Outils',
        'nav_use_cases' => 'Cas d\'utilisation',
        'nav_blog' => 'Blogue',
        'nav_pricing' => 'Tarifs',
        'nav_about' => 'À propos',
        'nav_docs' => 'Documentation',
        'nav_changelog' => 'Nouveautés',
        'nav_compare' => 'Comparer',
        'nav_enterprise' => 'Entreprise',
        'tools_hero_title' => '13,000+ outils IA — Une seule plateforme',
        'tools_hero_subtitle' => 'Recherchez, filtrez et explorez tous les outils qu\'Alfred a à offrir',
        'tools_search_placeholder' => 'Rechercher des outils...',
        'use_cases_title' => 'Alfred IA pour tout le monde',
        'use_cases_subtitle' => 'Découvrez comment Alfred aide les professionnels de tous les secteurs',
        'blog_title' => 'Blogue Alfred IA',
        'blog_subtitle' => 'Tutoriels, analyses et annonces',
        'pricing_title' => 'Tarification simple et transparente',
        'pricing_subtitle' => 'Commencez gratuitement, passez à la vitesse supérieure quand vous en avez besoin',
        'about_title' => 'À propos de GoSiteMe',
        'about_subtitle' => 'Construire l\'avenir de l\'IA depuis Montréal',
        'docs_title' => 'Documentation',
        'docs_subtitle' => 'Tout ce dont vous avez besoin pour intégrer Alfred',
        'changelog_title' => 'Nouveautés d\'Alfred',
        'compare_title' => 'Pourquoi Alfred gagne',
        'enterprise_title' => 'Alfred pour les entreprises',
        'cta_try_free' => 'Essayer Alfred gratuitement',
        'cta_start_trial' => 'Commencer l\'essai gratuit de 14 jours',
        'cta_view_pricing' => 'Voir les tarifs',
        'footer_tools' => 'Répertoire d\'outils',
        'footer_blog' => 'Blogue',
        'footer_docs' => 'Documentation',
        'footer_about' => 'À propos',
        'footer_changelog' => 'Journal des changements',
        'footer_compare' => 'Comparer',
        'footer_enterprise' => 'Entreprise',
        'footer_marketplace' => 'Marché',
        'nav_tools' => 'Outils',
        'nav_alfred' => 'Alfred IA',

        // ========== Sprint 1 & 2 Translation Keys ==========

        // Developer Portal
        'dev_portal_title' => 'Portail Développeur',
        'dev_portal_subtitle' => 'Construisez avec Alfred AI',
        'api_playground' => 'Terrain de jeu API',
        'api_keys' => 'Clés API',
        'generate_key' => 'Générer une clé API',
        'key_name' => 'Nom de la clé',
        'key_permissions' => 'Permissions',
        'webhooks' => 'Webhooks',
        'oauth_apps' => 'Applications OAuth',
        'rate_limits' => 'Limites de requêtes',
        'sdks' => 'Kits de développement',

        // Extensions
        'extensions_title' => 'Extensions Alfred AI',
        'chrome_extension' => 'Extension Chrome',
        'cli_tool' => 'Outil en ligne de commande',
        'install_extension' => 'Installer l\'extension',
        'extension_features' => 'Fonctionnalités de l\'extension',

        // IVR Builder
        'ivr_builder_title' => 'Constructeur de flux SVI',
        'ivr_subtitle' => 'Concevez des menus vocaux visuellement',
        'add_node' => 'Ajouter un nœud',
        'menu_node' => 'Menu',
        'greeting_node' => 'Accueil',
        'transfer_node' => 'Transfert',
        'voicemail_node' => 'Messagerie vocale',
        'condition_node' => 'Condition',
        'save_flow' => 'Sauvegarder le flux',
        'deploy_flow' => 'Déployer le flux',

        // Voice Cloning
        'voice_cloning_title' => 'Studio de clonage vocal',
        'clone_voice' => 'Clonez votre voix',
        'upload_sample' => 'Télécharger un échantillon vocal',
        'voice_profile' => 'Profil vocal',
        'voice_quality' => 'Qualité vocale',
        'train_model' => 'Entraîner le modèle',

        // Call Campaigns
        'call_campaigns_title' => 'Campagnes d\'appels',
        'create_campaign' => 'Créer une campagne',
        'campaign_name' => 'Nom de la campagne',
        'contact_list' => 'Liste de contacts',
        'campaign_script' => 'Script d\'appel',
        'schedule_campaign' => 'Planifier',
        'campaign_stats' => 'Statistiques de campagne',
        'calls_completed' => 'Appels terminés',
        'calls_pending' => 'Appels en attente',
        'success_rate' => 'Taux de succès',

        // Enterprise Admin
        'enterprise_admin_title' => 'Administration Entreprise',
        'org_settings' => 'Paramètres de l\'organisation',
        'team_members' => 'Membres de l\'équipe',
        'invite_member' => 'Inviter un membre',
        'member_role' => 'Rôle',
        'role_admin' => 'Administrateur',
        'role_manager' => 'Gestionnaire',
        'role_member' => 'Membre',
        'role_viewer' => 'Observateur',
        'audit_log' => 'Journal d\'audit',
        'sso_settings' => 'Paramètres SSO',
        'security_settings' => 'Paramètres de sécurité',
        'usage_quotas' => 'Quotas d\'utilisation',

        // Affiliate
        'affiliate_title' => 'Programme d\'affiliation',
        'affiliate_subtitle' => 'Gagnez 30% de commission récurrente',
        'referral_link' => 'Votre lien de parrainage',
        'total_referrals' => 'Total de parrainages',
        'total_earnings' => 'Gains totaux',
        'pending_payout' => 'Paiement en attente',
        'request_payout' => 'Demander un paiement',
        'affiliate_terms' => 'Conditions d\'affiliation',

        // Status Page
        'status_title' => 'État du système',
        'all_systems_operational' => 'Tous les systèmes opérationnels',
        'degraded_performance' => 'Performance dégradée',
        'partial_outage' => 'Panne partielle',
        'major_outage' => 'Panne majeure',
        'uptime' => 'Disponibilité',
        'response_time' => 'Temps de réponse',
        'incident_history' => 'Historique des incidents',

        // Analytics
        'analytics_title' => 'Analytique',
        'analytics_subtitle' => 'Comprenez vos habitudes d\'utilisation',
        'time_range' => 'Période',
        'today' => 'Aujourd\'hui',
        'last_7_days' => '7 derniers jours',
        'last_30_days' => '30 derniers jours',
        'last_90_days' => '90 derniers jours',
        'api_calls' => 'Appels API',
        'voice_minutes' => 'Minutes vocales',
        'active_agents' => 'Agents actifs',
        'tools_executed' => 'Outils exécutés',
        'fleet_uptime' => 'Disponibilité de la flotte',
        'storage_used' => 'Stockage utilisé',
        'top_tools' => 'Outils les plus utilisés',
        'agent_performance' => 'Performance des agents',
        'cost_analysis' => 'Analyse des coûts',
        'projected_cost' => 'Coût mensuel projeté',
        'activity_log' => 'Journal d\'activité',

        // Webhooks
        'webhooks_title' => 'Événements Webhook',
        'webhooks_subtitle' => 'Recevez des notifications en temps réel',
        'create_webhook' => 'Créer un Webhook',
        'webhook_url' => 'URL du Webhook',
        'webhook_events' => 'Événements',
        'webhook_secret' => 'Secret de signature',
        'webhook_active' => 'Actif',
        'webhook_paused' => 'En pause',
        'webhook_disabled' => 'Désactivé',
        'delivery_log' => 'Journal de livraison',
        'test_webhook' => 'Envoyer un test',
        'event_reference' => 'Référence des événements',

        // Marketplace Creator
        'creator_dashboard' => 'Tableau de bord créateur',
        'my_products' => 'Mes produits',
        'add_product' => 'Ajouter un produit',
        'product_earnings' => 'Revenus',
        'reviews_ratings' => 'Avis et notes',
        'creator_settings' => 'Paramètres créateur',
        'creator_analytics' => 'Analytique créateur',
        'total_downloads' => 'Téléchargements totaux',
        'total_revenue' => 'Revenu total',
        'average_rating' => 'Note moyenne',
        'publish_product' => 'Soumettre pour révision',
        'save_draft' => 'Sauvegarder comme brouillon',
        'product_type' => 'Type de produit',
        'product_category' => 'Catégorie',
        'product_tags' => 'Étiquettes',
        'product_price' => 'Prix',
        'commission_rate' => '70% de commission',
        'request_payout_btn' => 'Demander le paiement',
        'minimum_payout' => 'Paiement minimum: 25$',

        // SDKs Page
        'sdks_title' => 'Kits de développement Alfred AI',
        'sdks_subtitle' => 'Intégrez en quelques minutes',
        'quick_start' => 'Démarrage rapide',
        'installation' => 'Installation',
        'code_examples' => 'Exemples de code',
        'type_safe' => 'Sûr en types',
        'auto_retry' => 'Ré-essai automatique',
        'streaming_support' => 'Support du streaming',

        // Notifications
        'notifications' => 'Notifications',
        'mark_all_read' => 'Tout marquer comme lu',
        'no_notifications' => 'Aucune notification',
        'view_all' => 'Tout voir',
        'notification_preferences' => 'Préférences de notification',

        // Pricing (6 tiers)
        'plan_free' => 'Gratuit',
        'plan_starter' => 'Débutant',
        'plan_professional' => 'Professionnel',
        'plan_enterprise' => 'Entreprise',
        'plan_enterprise_plus' => 'Entreprise Plus',
        'plan_custom' => 'Sur mesure',
        'monthly_billing' => 'Mensuel',
        'annual_billing' => 'Annuel',
        'save_17_percent' => 'Économisez 17%',
        'per_month' => '/mois',
        'per_year' => '/an',
        'billed_annually' => 'Facturé annuellement',
        'contact_sales' => 'Contacter les ventes',
        'compare_plans' => 'Comparer les plans',
        'feature_comparison' => 'Comparaison des fonctionnalités',
        'overage_charges' => 'Frais de dépassement',

        // Common new terms
        'oauth' => 'OAuth',
        'authorization' => 'Autorisation',
        'scopes' => 'Portées',
        'access_token' => 'Jeton d\'accès',
        'refresh_token' => 'Jeton de renouvellement',
        'client_id' => 'Identifiant client',
        'client_secret' => 'Secret client',
        'redirect_uri' => 'URI de redirection',
        'revoke' => 'Révoquer',
        'expires' => 'Expire',
        'metered_billing' => 'Facturation à l\'usage',
        'current_usage' => 'Utilisation actuelle',
        'usage_limit' => 'Limite d\'utilisation',
        'unlimited' => 'Illimité',
        'api_reference' => 'Référence API',
        'getting_started' => 'Premiers pas',
        'documentation' => 'Documentation',
        'copy_to_clipboard' => 'Copier dans le presse-papiers',
        'copied' => 'Copié!',
        'loading' => 'Chargement...',
        'no_data' => 'Aucune donnée disponible',
        'error_occurred' => 'Une erreur est survenue',
        'try_again' => 'Réessayer',
        'confirm_action' => 'Êtes-vous sûr?',
        'yes_delete' => 'Oui, supprimer',
        'cancel' => 'Annuler',
        'save_changes' => 'Sauvegarder',
        'export_data' => 'Exporter les données',
        'import_data' => 'Importer les données',
        'filter_by' => 'Filtrer par',
        'sort_by' => 'Trier par',
        'ascending' => 'Croissant',
        'descending' => 'Décroissant',
        'showing_results' => 'Affichage des résultats',
        'no_results' => 'Aucun résultat trouvé',
        'items_per_page' => 'Éléments par page',

        'a11y_skip_to_main' => 'Aller au contenu principal',
        'a11y_main_nav' => 'Navigation principale',
        'a11y_site_footer' => 'Pied de page',
        'a11y_open_editor' => 'Ouvrir l\'éditeur directement',
        'a11y_back_to_top' => 'Retour en haut',
        'a11y_close_menu' => 'Fermer le menu',
        'a11y_account_nav' => 'Compte',
        'a11y_dashboard_btn' => 'Tableau de bord',
        'a11y_my_account_btn' => 'Mon compte',
        'a11y_language_label' => 'Langue',
    ],
];

// Hebrew: full catalog not translated yet — start from English; RTL shell strings (re-applied after lang_alfred.php merges into EN).
$root_he_shell = [
    'og_locale' => 'he_IL',
    'a11y_skip_to_main' => 'דלג לתוכן הראשי',
    'a11y_main_nav' => 'ניווט ראשי',
    'a11y_site_footer' => 'תחתית האתר',
    'a11y_open_editor' => 'פתח את העורך ישירות',
    'a11y_back_to_top' => 'חזרה למעלה',
    'a11y_close_menu' => 'סגור תפריט',
    'a11y_account_nav' => 'חשבון',
    'a11y_dashboard_btn' => 'לוח בקרה',
    'a11y_my_account_btn' => 'החשבון שלי',
    'a11y_language_label' => 'שפה',
];
$LANG_STRINGS['he'] = array_merge($LANG_STRINGS['en'], $root_he_shell);
